[November Update] NPC Shifts
LandSandBoat/server pull request #1044
Opened 2021-11-27 14:51 UTC by claywar

**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] that I agree to LandSandBoat's [Limited Contributor License Agreement](https://github.com/LandSandBoat/server/blob/base/.github/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I have **read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)**
- [x] that I've _**tested my code and things my code changed**_ since the last commit in the PR, and will test after any later commits

2021-11-28 21:06 UTC, TeoTwawki requested changes
Mob Names in promy zones are wrong, we want to at least partially fix this - the new apex stuff can be ignored till someone caps it, but we want a memory receptacle to be named correctly.

All the receptacles (as mobs) have wrong names, and in Promy Vahzl the normally hidden NPC has a monsters name by mistake (this is the npc we animate to show the portal).

Everything else checks out well enough - promy spires are reachable, portals work despite naming issues.

2021-11-29 17:31 UTC, claywar commented
Running some basic sanity on my end, but this should cover the above issues.

2021-11-30 19:57 UTC, kaincenteno commented
Awesome job Clay :D

2021-11-30 21:47 UTC, TeoTwawki approved these changes

2021-11-30 21:49 UTC, merged