[Proposal] Organize spell scripts in folders, depending of type
LandSandBoat/server pull request #1071
Opened 2021-12-04 01:16 UTC by Xaver-DaRed

**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] that I agree to LandSandBoat's [Limited Contributor License Agreement](https://github.com/LandSandBoat/server/blob/base/.github/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I have **read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)**
- [NO] that I've _**tested my code and things my code changed**_ since the last commit in the PR, and will test after any later commits

A proposal for a new spell organization, similar to how Blue Magic and Trusts are done. It follows in-game menu organization.
Things of note while this was done:
- We have 2 copies of Blue Spells out of bluemagic folder. They are also inside of bluemagic folder.
- We have 2 non-spell "global" scripts inside spells folder.
- We have a doom spell. It has no entry in database, unlike all other spells.

2021-12-04 01:26 UTC, claywar commented
I'm onboard with this.

2021-12-04 01:37 UTC, TeoTwawki commented
I'm on board with basically following the in game menu layout. diff menu selection = gets a diff directory path

There are a few spells that in retail are mob-only but are castable by players if set to be in the database (Curse comes to mind) we can reliably guess where these _would_ fit though.

2021-12-09 13:45 UTC, zach2good requested changes
Good idea, just needs some cleanup in core (I assume Lua is fine, I'm not going through 600+ files 👀)

It might be worth making a function in spellutils.cpp (or similar) to turn the `SPELLGROUP` enum into the desired string (using the switch I posted).

2021-12-09 13:45 UTC, zach2good commented on src/map/lua/luautils.cpp
> +        if (PSpell->getSpellGroup() == SPELLGROUP_WHITE)
Please change this to a `switch` statement:
```cpp
std::string switchKey = "";
switch (PSpell->getSpellGroup())
{
    case SPELLGROUP_WHITE:
    {
        switchKey = "white";
    }
    break;
    ...
    default:
    {
        ShowError(...);
    }
    break;
}

if (auto cached_func = lua["xi"]["globals"]["spells"][switchKey][name][funcName]; cached_func.valid())
{
    return cached_func;
}
...
```

2021-12-09 13:45 UTC, zach2good commented on src/map/spell.cpp
> +                if (PSpell->getSpellGroup() == SPELLGROUP_WHITE)
Same here, but you can do the format:
```cpp
std::string switchKey = "";

// Switch

filename = fmt::format("./scripts/globals/spells/{}/{}.lua", switchKey, PSpell->getName());
```

2021-12-09 21:45 UTC, zach2good approved these changes

2021-12-11 17:06 UTC, merged