Fix for Silent oils + Prism powders should always last 9m(Not Random) Issue #807
LandSandBoat/server pull request #1107
Opened 2021-12-14 19:20 UTC by hooksta4

**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] that I agree to LandSandBoat's [Limited Contributor License Agreement](https://github.com/LandSandBoat/server/blob/base/.github/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I have **read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)**
- [x] that I've _**tested my code and things my code changed**_ since the last commit in the PR, and will test after any later commits

2021-12-14 19:22 UTC, hooksta4 commented
So how am I messing this up? I created a new branch (silentoils) and then pushed to silentoils branch. Created a PR and it sticks the ones from yesterday in there? I dont get it?

2021-12-14 19:23 UTC, Xaver-DaRed commented
You have commits from a different PR here
This happened becouse you, at first, made those commits in base, and you forked from said base.

2021-12-14 19:25 UTC, hooksta4 commented
> You have commits from a different PR here This happened becouse you, at first, made those commits in base, and THEN you forked from said base.

How do I fix this? Delete that fork and redo it?

2021-12-14 19:27 UTC, Xaver-DaRed commented
ok so...
you have right now some PRs not merged.
I would wait until you get all open PRs merged into our base.
THEN, once that is done, I would pull a fresh copy. start clean

This is the easier way of doing it withought going into push and pulls

2021-12-14 19:27 UTC, TeoTwawki commented
IT IS TIME! 
To learn about.. 
[GIT REBASE!  ](https://www.google.com/search?hl=en&q=git%20rebase%20remove%20commits)

O.O

https://git-scm.com/docs/git-rebase

2021-12-14 19:28 UTC, hooksta4 commented
> IT IS TIME! To learn about.. [GIT REBASE! ](https://www.google.com/search?hl=en&q=git%20rebase%20remove%20commits)
> 
> O.O
> 
> https://git-scm.com/docs/git-rebase

Did you just quote Lion King?

2021-12-14 19:29 UTC, TeoTwawki commented
> > IT IS TIME! To learn about.. [GIT REBASE! ](https://www.google.com/search?hl=en&q=git%20rebase%20remove%20commits)
> > O.O
> > https://git-scm.com/docs/git-rebase
> 
> Did you just quote Lion King?

Possibly. But I don't think they used git.

:D

2021-12-14 19:31 UTC, hooksta4 commented
> commits in them.

You guys have been awesome, Thanks so much and sorry for the troubles. short story short, just wait until my branch is even with LSB as I am like 4 commits ahead. 

God damnit, I am going to git good at this... git it?

2021-12-14 19:33 UTC, hooksta4 commented
> od damnit, I am going to git good at this... git it?

I had an extra space that caused the style check to fail. updated locally, should I push or wait until everything is done?

2021-12-14 19:51 UTC, TeoTwawki commented
Leave this for now and after work (I get done somewhere after 5pm eastern) look for me on [discord](https://discord.gg/q4YTHkNVh7) and we'll fix this together

2021-12-14 19:59 UTC, hooksta4 commented
> Leave this for now and after work (I get done somewhere after 5pm eastern) look for me on [discord](https://discord.gg/q4YTHkNVh7) and we'll fix this together

Good deal, thanks!

2021-12-15 02:14 UTC, TeoTwawki commented
> hooksta4 deleted the Silentpots branch 6 minutes ago 

@hooksta4 oopsie?

2021-12-15 02:21 UTC, hooksta4 commented
> > hooksta4 deleted the Silentpots branch 6 minutes ago
> 
> @hooksta4 oopsie?

why yes in deed....

2021-12-15 02:56 UTC, hooksta4 commented
FFXIcylopedia has rainbow powder at 10 min. Reflected as such.

2021-12-15 12:10 UTC, Xaver-DaRed commented
Clopedia also states that it last from 1 second to 10 minutes. so, a range.

2021-12-15 12:12 UTC, hooksta4 commented
For which one or all of them ?

2021-12-15 12:13 UTC, Xaver-DaRed commented
Since we are changing them all, all of them.

I find it hard to believe that rainbow powder has only 1 min boon over prism

2021-12-15 12:17 UTC, hooksta4 commented
Fair enough, I would default back to @ShiyoKozuki , the OP to provide that detail?

2021-12-15 12:24 UTC, TeoTwawki commented
> Clopedia also states that it last from 1 second to 10 minutes. so, a range.
> 
> We need retail confirmation of this items. Too much conflicting information.

@Xaver-DaRed SE dropped ranged. But the advantage of rainbow over prism was always the longer duration When SE bumped up prism they may not have done the same sized increase to rainbow - depends on if they increased the base or the total

2021-12-15 13:45 UTC, TeoTwawki commented
retail confirmation all of them including rainbow are 10 min now. old duration on rainbow was 3 min non random. wiki's display of 1 second is for the activation time they just have a template that misleads but when you mouse hover it explains.

so all of these are 600 seconds, but when you receive the icon you'd already lost 1 second and it only displays minutes so shows as 9.

2021-12-15 14:02 UTC, TeoTwawki commented on scripts/globals/items/pinch_of_rainbow_powder.lua
> +    if (target:hasStatusEffect(xi.effect.INVISIBLE)) then
this check isn't needed, there is no harm, nor is the delete, invisible already overwrites itself

2021-12-15 14:51 UTC, hooksta4 commented
A few cleanup things to address, when applying silent pot when already under status effect sneak - does it give message No_effect in retail behavior? Or nothing?

2021-12-15 15:37 UTC, Omnione commented
> A few cleanup things to address, when applying silent pot when already under status effect sneak - does it give message No_effect in retail behavior? Or nothing?

Retail uses "Has no effect".

2021-12-15 15:44 UTC, hooksta4 commented
> > A few cleanup things to address, when applying silent pot when already under status effect sneak - does it give message No_effect in retail behavior? Or nothing?
> 
> Retail uses "Has no effect".

Thanks

2021-12-15 16:38 UTC, almuth150 commented
Was there a reason for dropping the sneak/invis multiplier? It doesn't appear to be a setting that has fallen into disuse.

2021-12-15 16:41 UTC, hooksta4 commented
Yes

2021-12-19 20:47 UTC, Xaver-DaRed requested changes
Please, add back the xi.settings.SNEAK_INVIS_DURATION_MULTIPLIER to durations. Mostly becouse we still support that setting... At least for now. There's no reson to reduce it's functionality.

Other than that, this seems good.

2021-12-20 16:24 UTC, hooksta4 commented
> 

Ok, I removed it because its linking to settings SNEAK_INVIS_DURATION_MULTIPLIER, which is 1 by default... not gear (which none of the enhance sneak/invis equip is coded yet) but understand why it would want to be back in there.

2021-12-20 16:28 UTC, TeoTwawki commented on scripts/globals/items/pinch_of_prism_powder.lua
>  end
indentation in this file got moved incorrectly in 2 places.

2021-12-20 16:28 UTC, TeoTwawki commented on scripts/globals/items/pinch_of_rainbow_powder.lua
> +local duration = (600)
here too

2021-12-20 16:29 UTC, TeoTwawki commented on scripts/globals/items/pot_of_silent_oil.lua
> +    local duration = (600)
1. parenthesis not needed
2. 2 now that its not random, it doesn't even need variablized

2021-12-20 16:29 UTC, TeoTwawki commented on scripts/globals/items/pot_of_silent_oil.lua
> +    local duration = (600)
same in other places

2021-12-20 16:33 UTC, Xaver-DaRed requested changes
Some styiling changes needed. TY for bringing back the setting. It is meant for server customization and probably rendered useless with this changes, but still.

2021-12-20 16:33 UTC, Xaver-DaRed commented on scripts/globals/items/pinch_of_prism_powder.lua
> +local duration = (600)
Aligninment: Insert 4 spaces to this line.
Remove the parenthesis ( ) arround 600

2021-12-20 16:33 UTC, Xaver-DaRed commented on scripts/globals/items/pinch_of_prism_powder.lua
> +        target:addStatusEffect(xi.effect.INVISIBLE, 1, 10, math.floor(duration * xi.settings.SNEAK_INVIS_DURATION_MULTIPLIER))
Alignment: Remove 4 spaces from this line.

2021-12-20 16:33 UTC, Xaver-DaRed commented on scripts/globals/items/pinch_of_rainbow_powder.lua
> +        target:addStatusEffect(xi.effect.INVISIBLE, 1, 10, math.floor(duration * xi.settings.SNEAK_INVIS_DURATION_MULTIPLIER))
Alignment: Remove 4 spaces from this line.

2021-12-20 16:33 UTC, Xaver-DaRed commented on scripts/globals/items/pinch_of_rainbow_powder.lua
> +local duration = (600)
Aligninment: Insert 4 spaces to this line.
Remove the parenthesis ( ) arround 600

2021-12-20 16:33 UTC, Xaver-DaRed commented on scripts/globals/items/pot_of_silent_oil.lua
> +    local duration = (600)
Remove the parenthesis ( ) arround 600

2021-12-20 16:39 UTC, hooksta4 commented on scripts/globals/items/pinch_of_rainbow_powder.lua
> +local duration = (600)
removed entire variable.

2021-12-20 16:41 UTC, hooksta4 commented on scripts/globals/items/pinch_of_rainbow_powder.lua
> +        target:addStatusEffect(xi.effect.INVISIBLE, 1, 10, math.floor(duration * xi.settings.SNEAK_INVIS_DURATION_MULTIPLIER))
21 yea?

2021-12-20 16:42 UTC, hooksta4 commented on scripts/globals/items/pinch_of_rainbow_powder.lua
> +        target:addStatusEffect(xi.effect.INVISIBLE, 1, 10, math.floor(duration * xi.settings.SNEAK_INVIS_DURATION_MULTIPLIER))
`item_object.onItemUse = function(target)
    if target:hasStatusEffect(xi.effect.INVISIBLE) then
        target:delStatusEffect(xi.effect.INVISIBLE)
    end
    target:addStatusEffect(xi.effect.INVISIBLE,1,10, math.floor(600 * xi.settings.SNEAK_INVIS_DURATION_MULTIPLIER))
end`

2021-12-20 16:42 UTC, Xaver-DaRed commented on scripts/globals/items/pinch_of_rainbow_powder.lua
> +        target:addStatusEffect(xi.effect.INVISIBLE, 1, 10, math.floor(duration * xi.settings.SNEAK_INVIS_DURATION_MULTIPLIER))
yes

2021-12-20 16:44 UTC, TeoTwawki commented on scripts/globals/items/pinch_of_rainbow_powder.lua
> +        target:addStatusEffect(xi.effect.INVISIBLE, 1, 10, math.floor(duration * xi.settings.SNEAK_INVIS_DURATION_MULTIPLIER))
actually while here line breaks between blocks of code are nice:
```lua
if conditions then
    code
end

more code
```

2021-12-20 16:56 UTC, Xaver-DaRed approved these changes

2021-12-20 17:07 UTC, TeoTwawki approved these changes

2021-12-20 17:23 UTC, merged