[Sky] Implement yellow teleport functionality and zone cleanup
LandSandBoat/server pull request #1167
Opened 2022-01-07 15:58 UTC by Xaver-DaRed

**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] that I agree to LandSandBoat's [Limited Contributor License Agreement](https://github.com/LandSandBoat/server/blob/base/.github/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I have **read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)**
- [x] that I've _**tested my code and things my code changed**_ since the last commit in the PR, and will test after any later commits

Disables yellow teleporters when Sky Gods are spawned.
General zone clean-up

2022-01-12 12:12 UTC, zach2good requested changes
Seems reasonable, just one typo in there

2022-01-12 12:12 UTC, zach2good commented on scripts/zones/RuAun_Gardens/mobs/Byakko.lua
> +    GetNPCByID(ID.npc.PORTAL_TO_GENBU):setAnimation(xi.anim.CLOSE_DOOR)
Should this be `PORTAL_TO_BYAKKO`?

2022-01-12 17:54 UTC, Xaver-DaRed commented on scripts/zones/RuAun_Gardens/mobs/Byakko.lua
> +    GetNPCByID(ID.npc.PORTAL_TO_GENBU):setAnimation(xi.anim.CLOSE_DOOR)
very true. fixed

2022-01-15 14:05 UTC, zach2good approved these changes

2022-01-15 14:05 UTC, merged