Adding AE to items Round 1
LandSandBoat/server pull request #1265
Opened 2022-02-09 02:00 UTC by hooksta4

**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] that I agree to LandSandBoat's [Limited Contributor License Agreement](https://github.com/LandSandBoat/server/blob/base/.github/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I have **read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)**
- [x] that I've _**tested my code and things my code changed**_ since the last commit in the PR, and will test after any later commits

2022-02-09 02:29 UTC, RuthlessMortal commented
I will say that need to fix some of the Styles

Example 

Don't 
--INSERT INTO `item_mods` VALUES (17774,431,1);   -- Additional effect: Light Damage (Type DAMAGE)--shiranui 17774

Do
-- INSERT INTO `item_mods` VALUES (17774,431,1);   -- Additional effect: Light Damage (Type DAMAGE) -- shiranui 17774

Where you have -- there needs to be space you can find the error that show up in Style Check for ones to fix

At least that what I am see currently

2022-02-09 03:28 UTC, hooksta4 commented
> 17774,431,1

JFC, the one thing I specifically went in to fix I didnt smh Fix incoming. My eyes are bleeding.

2022-02-09 03:57 UTC, RuthlessMortal commented on sql/item_mods.sql
> +INSERT INTO `item_mods` VALUES (16937,431,1);   --Icicle Sword (Additional effect: Ice Damage)
Need space on  --Icicle Sword

2022-02-09 03:58 UTC, hooksta4 commented
Yea just fixed it too. I’m going to bed been staring at it too long today.

On Tue, Feb 8, 2022 at 10:57 PM RuthlessMortal ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In sql/item_mods.sql
> <https://github.com/LandSandBoat/server/pull/1265#discussion_r802249486>:
>
> >  INSERT INTO `item_mods` VALUES (16936,501,10);  -- Additional effect Chance 10%
>  INSERT INTO `item_mods` VALUES (16936,950,8);   -- Additional effect element Darkness (xi.magic.element)
>  INSERT INTO `item_mods` VALUES (16937,16,8); -- ICE_RES
> -INSERT INTO `item_mods` VALUES (16937,431,1);   -- Additional effect: Ice Damage (Type DAMAGE)--icicle_sword 16937
> +INSERT INTO `item_mods` VALUES (16937,431,1);   --Icicle Sword (Additional effect: Ice Damage)
>
> Need space on --Icicle Sword
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/LandSandBoat/server/pull/1265#pullrequestreview-876898138>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADKKD3X3U5OZGRF24DSAB23U2HQ2ZANCNFSM5N4ER65Q>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>
-- 
Carl L. Hooker

2022-02-09 08:23 UTC, Xaver-DaRed requested changes
The changes themselves seem reasonable. Just fix the 3 missing spaces and I'd say this is good to go.

2022-02-09 08:23 UTC, Xaver-DaRed commented on sql/item_mods.sql
> +INSERT INTO `item_mods` VALUES (16937,431,1);   --Icicle Sword (Additional effect: Ice Damage)
Missed one.

2022-02-09 08:23 UTC, Xaver-DaRed commented on sql/item_mods.sql
> +INSERT INTO `item_mods` VALUES (18009,345,1000);-- Martial Knife: TP Bonus +1000
Missed another here.

2022-02-09 08:23 UTC, Xaver-DaRed commented on sql/item_mods.sql
> +INSERT INTO `item_mods` VALUES (18221,345,1000);-- Martial Bhuj: TP Bonus +1000
And another one here.

2022-02-09 16:26 UTC, tristamgreen commented on sql/item_mods.sql
> +INSERT INTO `item_mods` VALUES (18294,431,2);   -- BROvura (Additional effect: EVASION_DOWN)
Brovura

2022-02-09 16:29 UTC, hooksta4 commented on sql/item_mods.sql
> +INSERT INTO `item_mods` VALUES (18294,431,2);   -- BROvura (Additional effect: EVASION_DOWN)
weird typo - will fix it in next round.

2022-02-09 19:04 UTC, hooksta4 commented on sql/item_mods.sql
> +INSERT INTO `item_mods` VALUES (18294,431,2);   -- BROvura (Additional effect: EVASION_DOWN)
actually, upon consideration, i will not change it as its a comment and someone else will have to PR an A instead of an O

2022-02-09 19:06 UTC, TeoTwawki commented on sql/item_mods.sql
> +INSERT INTO `item_mods` VALUES (18294,431,2);   -- BROvura (Additional effect: EVASION_DOWN)
![image](https://user-images.githubusercontent.com/6871475/153272056-904d3739-0892-4b29-a2ac-ab154ffb2f4b.png)

:joy:

2022-02-09 19:07 UTC, TeoTwawki commented on sql/item_mods.sql
> +INSERT INTO `item_mods` VALUES (18294,431,2);   -- BROvura (Additional effect: EVASION_DOWN)
the great axe that calls everyone dude or bro: dudura

2022-02-09 19:09 UTC, hooksta4 commented on sql/item_mods.sql
> +INSERT INTO `item_mods` VALUES (18294,431,2);   -- BROvura (Additional effect: EVASION_DOWN)
should have made it bruhvura then

2022-02-09 19:20 UTC, TeoTwawki commented on sql/item_mods.sql
> +INSERT INTO `item_mods` VALUES (18294,431,2);   -- BROvura (Additional effect: EVASION_DOWN)
![image](https://user-images.githubusercontent.com/6871475/153274491-15127e0f-836c-4a20-80cb-d06185e5aa5c.png)

2022-02-09 19:54 UTC, TeoTwawki commented on sql/item_mods.sql
> +INSERT INTO `item_mods` VALUES (18294,431,2);   -- BROvura (Additional effect: EVASION_DOWN)
i ninja'd a commit to your branch

2022-02-11 15:57 UTC, Xaver-DaRed approved these changes

2022-02-11 17:31 UTC, merged