Fix shrouded bijou
LandSandBoat/server pull request #1297
Opened 2022-02-17 04:17 UTC by beneliezer

**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] that I agree to LandSandBoat's [Limited Contributor License Agreement](https://github.com/LandSandBoat/server/blob/base/.github/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I have **read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)**
- [x] that I've _**tested my code and things my code changed**_ since the last commit in the PR, and will test after any later commits

It seems that Shrouded Bijou drops are really messed up in Dynamis - Xarcbard. I've added the item to several NM's that were missing it, and updated the drop rates in accordance with the "TH Level" chart from SE, using the TH0/TH2 columns from FFXIDB for each NM.
![image](https://user-images.githubusercontent.com/65316697/154404222-332c71c0-eeb4-4d85-936e-e153ec5845d7.png)
![image](https://user-images.githubusercontent.com/65316697/154404256-0a889465-a19c-4e30-9f4f-171c693469d7.png)

2022-02-17 08:37 UTC, Xaver-DaRed approved these changes
Numbers look reasonable.

SQUASH when mergin!

2022-02-17 12:23 UTC, claywar commented
There's a lot of things going on here that shouldn't be part of this PR.  If you're having difficulties rebasing, I would suggest starting with a fresh branch off of base and applying only the DB changes relevant.

2022-02-17 12:24 UTC, claywar requested changes
See previous comment.  Sparkshop and other commit history should not be included for DB changes.

2022-02-17 12:25 UTC, beneliezer commented
Yeah I wasn’t sure if all of that stuff was visible to you guys…. This is
solid advice. I’ll try to rebase/reset and if I can’t get it I’ll start
over. Thanks

On Thu, Feb 17, 2022 at 7:23 AM claywar ***@***.***> wrote:

> There's a lot of things going on here that shouldn't be part of this PR.
> If you're having difficulties rebasing, I would suggest starting with a
> fresh branch off of base and applying only the DB changes relevant.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/LandSandBoat/server/pull/1297#issuecomment-1042895027>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APSKOWKGN46AXMVD7UOMXLLU3TSDNANCNFSM5OTQZXKQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-02-17 13:09 UTC, TeoTwawki requested changes
https://docs.github.com/en/get-started/using-git/about-git-rebase

...or via tortoise: [linky because github doesn't like h265 I guess](https://user-images.githubusercontent.com/6871475/154487951-fb9780f6-ee83-47ce-9efb-4641fd9ae978.mp4)

2022-02-18 03:42 UTC, claywar approved these changes

2022-02-18 03:45 UTC, claywar commented
Queued CI to run again, something hinky happened with the Linux build while grabbing dependencies.

2022-02-18 03:45 UTC, TeoTwawki approved these changes

2022-02-18 03:47 UTC, TeoTwawki commented
> Queued CI to run again, something hinky happened with the Linux build while grabbing dependencies.

multiple force push/close+reopen in a short time tends to temporarily break the CI

2022-02-18 04:00 UTC, beneliezer commented
thanks for helping me figure this out!! >.<

2022-02-18 22:57 UTC, merged