[module] Changed module initialization order
LandSandBoat/server pull request #1358
Opened 2022-03-04 03:49 UTC by m241dan

**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] that I agree to LandSandBoat's [Limited Contributor License Agreement](https://github.com/LandSandBoat/server/blob/base/.github/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I have **read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)**
- [x] that I've _**tested my code and things my code changed**_ since the last commit in the PR, and will test after any later commits

It seemed to me that loading modules and then potentially loading other lua stuff (such as spells) is a bit counter productive. Modules should probably be loaded last so that modules effecting spells are not overwritten.

2022-03-04 06:25 UTC, zach2good requested changes
This (probably) breaks the module: `conquest_regional_npcs_always_up`

The problem here is that the initialisation order for modules needs to be:
```
Original Lua is loaded -> module is loaded -> function is called (or variable is read, you can have plain variables in the cache)
```

Moving the module init here (to where it used to be) breaks any zone-based overrides because it's hooking after the zone Lua init calls have happened in `zoneutils::LoadZoneList();`

> It seemed to me that loading modules and then potentially loading other Lua stuff (such as spells) is a bit counterproductive.

It isn't ideal, but since we have such tight coupling between core-object inits and their associated Lua inits, it isn't simple to load modules at exactly the right time. Currently, we only have modules that affect scripts in the root of `scripts/globals`, and nobody has raised an issue or complained about anything breaking since the change, so until we have the need to extend/fix it, it's fine as it is 🤷

2022-03-04 06:40 UTC, bope12 commented
> 

Having it where it load where it is now breaks overriding npc and mob scripts Override:new will run into nil zone tables

2022-03-04 13:23 UTC, m241dan commented
Ya, changing spells or npcs didn't work where it was because the module got
overwritten by the actual load.

I'll have to look at the conquest module, perhaps a two stage load?

On Thu, Mar 3, 2022, 11:40 PM bope12 ***@***.***> wrote:

> Having it where it load where it is now breaks overriding npc and mob
> scripts Override:new will run into nil zone tables
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/LandSandBoat/server/pull/1358#issuecomment-1058879893>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AA3KLWLKENNPXUCZAHO63GDU6GV53ANCNFSM5P4NSAIQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-03-04 15:22 UTC, m241dan commented
@zach2good Is there a reason we load Lua piece-meal like this?

Why not just have a base script that loads everything?

So, instead of having "local objects" in the scripts that are returned or what have you, why not just have it load itself directly into the global lua state? That's all C++ does but in a piece-meal way.

Instead of
```lua
local spell_object = {}

spell_object.functionOne = function(...) ... end

return spell_object

```

Something like this (can even drop the `.globals.` bit; which would make it more consistent anyway):

```lua
-- assume the base script that loaded us has already made sure black exists.
-- and if not, it would error out on load and we'd know immediately something was wrong
xi.globals.spells.black.gravity.someFunction = function(...) ... end

```

And there is some base load script in each folder that loads everything. Then "init lua" would just load one base load script that would then recursively search for others like it and populate the global xi table (essentially).

Then, at the end of this init, we could load modules and then when zone inits, it's all good.

Would be a bit of a pain setup but not too much work with sed or a little python script to make the changes. And I'm sure there are corner cases we'll have to work through, but it seems like it would make a little more sense than coupling the loading of the lua to C++ in the way that it is now.

Thoughts? What am I missing?

2022-03-04 15:30 UTC, zach2good commented
There is an issue if we were to preload _everything_: the Lua memory usage skyrockets from 30mb to 450mb-ish, which is unacceptable given that the regular memory usage for the whole program is about 700mb.

Items are the main problem here, but I think it's important to only pre-load the absolute minimum amount of stuff into the cache as possible.

2022-03-04 15:48 UTC, claywar commented
Given that we already have overrides using Interaction Framework for NPCs, Zones, and certain mob actions. I'm very hesitant with him wanting modules touching NPCs/Zones/Etc as well.  For changes to those, I think it would be much safer to either create a hidden quest, or modify existing scripts to accomplish goals on that end.

2022-03-04 15:50 UTC, m241dan commented
> There is an issue if we were to preload _everything_: the Lua memory usage skyrockets from 30mb to 450mb-ish, which is unacceptable given that the regular memory usage for the whole program is about 700mb.
> 
> Items are the main problem here, but I think it's important to only pre-load the absolute minimum amount of stuff into the cache as possible.

Really? I feel like it all gets loaded anyway by the following calls to init.

Is this a report from this?: https://github.com/LandSandBoat/server/blob/ca47aacb12781a68922aa6c9d60f6146cac93c0c/src/map/lua/luautils.cpp#L249

2022-03-04 15:51 UTC, m241dan commented
> Given that we already have overrides using Interaction Framework for NPCs, Zones, and certain mob actions. I'm very hesitant with him wanting modules touching NPCs/Zones/Etc as well. For changes to those, I think it would be much safer to either create a hidden quest, or modify existing scripts to accomplish goals on that end.

Perhaps I misunderstood the purpose of these modules then?

I would prefer never to modify existing scripts to accomplish my customization goals. And I thought that is what they were for?

2022-03-05 14:29 UTC, zach2good commented
> to accomplish my customization goals.

What are your goals?

2022-03-05 15:33 UTC, m241dan commented
> > to accomplish my customization goals.
> 
> What are your goals?

Well, the list is extensive but most of them are Lua based so that's why I prize this module system. Makes staying current with the ole Sand Ship easy without all the headaches of merge conflicts, etc. 

Anyway, here's brief overview of some select ones:
* Custom Spells and Ability parameters
  * Gravity 50% base instead of the now 26%
  * Innin, Yonin, Seigan, Hasso last for 60 minutes instead of 5 minutes
* Custom shops
  * I stock Brave Ox with Scholar spells since I don't have WotG areas open
  * I stock some lowbie weapons in various shops for jobs like Ninja and Samura since I unlock those at the start and don't stock the auction house.
* I have a very customized Casket system that yields either a set of pre-augmented items or augments themselves as items that are tradeable.
* Items such as Nexus Cape have a much shorter cooldown and much larger range of areas they can warp you to.
* Various Field of Valor page completions also yield more tradeable augments

Anyway, I could go on. But, most aspects of the above list are done via Lua and so having a nice set of modules to make those changes instead of modifying the existing scripts maintained by the Sand Ship makes it easier for me to stay up to date and contribute back (again, for reasons that I listed above).

If that is not the intent of the modules, then I apologize for wasting your time. I'm going to go ahead and close this PR for now and circle back to it at a later date when I perhaps have a more palatable solution for you.

2022-03-05 15:33 UTC, closed without merging

2022-03-19 15:24 UTC, zach2good commented
This is now addressed in: https://github.com/LandSandBoat/server/pull/1110

Load order is dynamic, and modules are applied when the scripts are cached. This might mean that things that aren't cached on startup (like spells and items) will emit a warning, but the override will still apply fine when the spell/item is eventually cached on use.