add tigerhunter.lua
LandSandBoat/server pull request #1637
Opened 2022-04-27 01:00 UTC by Grahf0085

**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x ] that I agree to LandSandBoat's [Limited Contributor License Agreement](https://github.com/LandSandBoat/server/blob/base/.github/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I have **read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)**
- [x] that I've _**tested my code and things my code changed**_ since the last commit in the PR, and will test after any later commits

2022-04-27 01:03 UTC, TeoTwawki approved these changes, later dismissed
thats not how these are handled anymore. To add additional effects you just add item mods now.

2022-04-27 01:05 UTC, TeoTwawki requested changes
~~see existing examples in item mods~~
Here is who it would look:
```sql
-- Tigerhunter 
INSERT INTO `item_mods` VALUES (16672,431,2);   -- Additional effect type: DEBUFF (PARALYSIS)
INSERT INTO `item_mods` VALUES (16672,499,11);  -- Additional effect animation (subEffect) xi.subEffect.PARALYSIS
INSERT INTO `item_mods` VALUES (16672,501,10);  -- Additional effect Chance 10%
```
Assuming the rate is really 10% that is

2022-04-27 11:14 UTC, TeoTwawki commented on sql/item_mods.sql
> +INSERT INTO item_mods VALUES (16672,431,2);  -- Additional effect type: DEBUFF (PARALYSIS)
you left out the item name

2022-04-27 11:15 UTC, TeoTwawki commented on sql/item_mods.sql
> +INSERT INTO item_mods VALUES (16672,431,2);  -- Additional effect type: DEBUFF (PARALYSIS)
```sql
INSERT INTO `item_mods` VALUES (16669,23,5);

-- Tigerhunter
INSERT INTO item_mods VALUES (16672,431,2);  -- Additional effect type: DEBUFF (PARALYSIS)
```

2022-04-27 11:55 UTC, claywar reviewed
This weapon should be additional effect paralysis vs tigers only. Is this handled?

2022-04-27 12:00 UTC, TeoTwawki commented
> This weapon should be additional effect paralysis vs tigers only. Is this handled?

@Grahf0085 you'll need to use latent effect table for that sort of case Grahf. 

```cpp
    VS_ECOSYSTEM         = 59, // Vs. Specific Ecosystem ID (e.g. Vs. Birds: Accuracy+3)
    VS_FAMILY            = 60, // Vs. Specific Family ID (e.g. Vs. Apkallu: Accuracy+3)
```

2022-04-27 12:25 UTC, Grahf0085 commented
> 
In my lua I have 
` if (target:getFamily() == 242) then`
Let that line out of the lua when I was translatint to LSB format.
I'll look into adding it to the SQL. Thank you

2022-06-02 23:16 UTC, claywar commented
Closing this PR for now.  If updates are made, please re-open and we'll be happy to review!

2022-06-02 23:16 UTC, closed without merging