Fix Some ToAU Instance Blackscreens
LandSandBoat/server pull request #176
Opened 2021-05-21 21:15 UTC by Era-Lusiphur

Players completing ToAU 31 Shades of Vengeance battlefield and possibly players completing Assaults in Periqia (the later untested) were met with a black screen on CS 102 firing on instance completion. On local server, this was due to instance returning nil by this point in the process (instance complete-> play CS -> check for instance -- what instance?).

Simply removing these checks for the instance status on the victory animation removes the possibility of any of these issues. A user receiving that CS will be completing their instance anyway or will be a GM firing it intentionally.

Upon examination of Ilrusi Atol, I saw similar checks and feel it's best to remove them as well. Again, I don't believe it's necessary due to what has to happen for that event to fire.

Following the CS (a simple warping animation), the player is sent to the destination zone that interprets where they land from their prior zone in onZoneIn.

Also removed a few unnecessary parenthesis per style guide.

**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] that I agree to LandSandBoat's [Limited Contributor License Agreement](https://github.com/LandSandBoat/server/blob/base/.github/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I have **read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)**
- [x] that I've _**tested my code and things my code changed**_ since the last commit in the PR, and will test after any later commits

2021-05-21 21:23 UTC, Era-Lusiphur commented
To save anyone the moment of checking, Mamool Ja Training Grounds was already setup this way without parenthesis.

2021-05-21 21:24 UTC, wrenffxi requested changes

2021-05-21 21:24 UTC, wrenffxi commented on scripts/zones/Ilrusi_Atoll/Zone.lua
> +        v:setPos(0, 0, 0, 0, 54)
undefined variable `v`

2021-05-21 21:24 UTC, wrenffxi commented on scripts/zones/Periqia/Zone.lua
> +        v:setPos(0, 0, 0, 0, 79)
undefined variable `v`

2021-05-21 21:26 UTC, KnowOne134 commented on scripts/zones/Periqia/Zone.lua
> +        v:setPos(0, 0, 0, 0, 79)
Even if you don't use instance, you killed the loop therfore v variable means nothing. Player:setPos()

2021-05-21 21:27 UTC, Era-Lusiphur commented
Ah. How embarrassing. Corrected hasty edit.

2021-05-22 18:29 UTC, megberry approved these changes

2021-05-22 18:31 UTC, wrenffxi approved these changes

2021-05-23 10:28 UTC, merged