Implement a basic 'Bloody Caress' mob TP skill
LandSandBoat/server pull request #195
Opened 2021-05-25 22:51 UTC by mrhappyasthma

There is not a whole lot of info about this spell available online, so I implemented a basic version similar to `Goblin Rush`, which is also a physical 3-hit spell.

I confirmed the animation matches retail videos from youtube.

**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] that I agree to LandSandBoat's [Limited Contributor License Agreement](https://github.com/LandSandBoat/server/blob/base/.github/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I have **read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)**
- [x] that I've _**tested my code and things my code changed**_ since the last commit in the PR, and will test after any later commits

2021-05-25 23:07 UTC, TeoTwawki commented on scripts/globals/mobskills/bloody_caress.lua
> +    -- TODO: Once `Floral Bouquet` TP move is implemented, this skill is eligible to target
Ty for the todo note, and thank you for conservative mod data on initial implementation.

2021-05-26 01:29 UTC, mrhappyasthma commented
Done as part of https://github.com/LandSandBoat/server/issues/202

2021-05-26 16:16 UTC, zach2good requested changes
It would be good if you also left something like this comment in the header for future readers:
```
There is not a whole lot of info about this spell available online, so I implemented a basic version similar to Goblin Rush, which is also a physical 3-hit spell.
```

2021-05-27 04:00 UTC, mrhappyasthma commented
Added the note. Please take another look.

2021-05-27 06:14 UTC, zach2good approved these changes

2021-05-27 13:05 UTC, merged