Fix Content Restriction
LandSandBoat/server pull request #2191
Opened 2022-07-04 21:44 UTC by The-Aerec

Co-Authored-By: Ophelia <heliashelium@gmail.com>

**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I've _**tested my code and the things my code has changed**_ since the last commit in the PR, and will test after any later commits

## What does this pull request do?

Fixes Content_restrict setting in main settings

## Steps to test these changes

enable/disable content and then turn on content restriction

2022-07-04 21:50 UTC, zach2good reviewed
Do we use `GetSettingsVariable` in many places? Now that we have direct access to the settings (and there are more settings areas than just main) we can probably rip out this binding

2022-07-04 22:03 UTC, The-Aerec commented
> Do we use GetSettingsVariable in many places? Now that we have direct access to the settings (and there are more settings areas than just main) we can probably rip out this binding

No not really. I didn't find many uses. This was just the: The quick fix Ophie and I found that fixed the issue.

2022-07-05 07:05 UTC, zach2good commented
Replace then I think, then it's clear what file the setting is being read from, and it's easier to move them around in the future without breaking things

2022-07-05 13:43 UTC, zach2good requested changes
Almost there

2022-07-05 13:43 UTC, zach2good commented on sql/npc_list.sql
> +INSERT INTO `npc_list` VALUES (17093448,'Shantotto','Shantotto',0,0.000,0.000,0.000,32768,50,50,0,1,0,6,27,0x0100060600101320133013401350006000700000,32,'TOAU',0);
Nice catch

2022-07-05 13:43 UTC, zach2good commented on src/map/utils/zoneutils.cpp
> +        uint8 normalLevelRangeMax = settings::get<int>("main.NORMAL_MOB_MAX_LEVEL_RANGE_MAX");
Keep an eye on what types you're getting, this is a truncation: int -> uint8. 

I think for most of these settings that you've replaced, you should be asking for bool or uint8

2022-07-05 13:43 UTC, zach2good commented on src/map/lua/luautils.cpp
> +                contentEnabled = (settings::get<int>(fileName)) != 0;
This section could be:
```cpp
contentEnabled = settings::get<bool>(fmt::format("main.{}", contentVariable));
```

2022-07-05 13:43 UTC, zach2good commented on src/map/lua/luautils.cpp
> +        contentRestrictionEnabled = settings::get<int>("main.RESTRICT_CONTENT") != 0;
contentRestrictionEnabled is a bool, ask settings for a bool: settings::get<bool>

If it's a 1 in the settings, it'll automagically convert it during lookup

2022-07-05 13:43 UTC, zach2good commented on src/map/battlefield.cpp
> +            cap = settings::get<int>("main.MAX_LEVEL"); // Cap to server max level to strip buffs - this is the retail diff between uncapped and capped to max lv.
cap is uint8, ask settings for uint8

2022-07-05 14:02 UTC, zach2good requested changes

2022-07-05 14:02 UTC, zach2good commented on src/map/lua/luautils.cpp
> +                contentEnabled = settings::get<bool>(fmt::format("main.{}", contentVariable)) != 0;
No need for ` != 0;`, this is now a bool of its own and doesn't need to converted into one

2022-07-05 14:02 UTC, zach2good commented on src/map/lua/luautils.cpp
> +        contentRestrictionEnabled = settings::get<bool>("main.RESTRICT_CONTENT") != 0;
Same here

2022-07-05 14:19 UTC, zach2good approved these changes
🎉

2022-07-05 14:20 UTC, claywar approved these changes

2022-07-05 14:32 UTC, TeoTwawki commented on sql/npc_list.sql
> +INSERT INTO `npc_list` VALUES (17093448,'Shantotto','Shantotto',0,0.000,0.000,0.000,32768,50,50,0,1,0,6,27,0x0100060600101320133013401350006000700000,32,'TOAU',0);
OH HOHO h...oh oh?

2022-07-05 14:33 UTC, merged

2022-07-05 14:34 UTC, TeoTwawki commented
> Do we use `GetSettingsVariable` in many places? Now that we have direct access to the settings (and there are more settings areas than just main) we can probably rip out this binding

historical footnote: we used to use it for some more things that no longer exist. old old oooold times you'd have to go way back in history to see.