BCNM Dropping Like Flies Fix
LandSandBoat/server pull request #2270
Opened 2022-07-12 22:35 UTC by dallano

Video and wiki link used as basis for changes:
https://ffxiclopedia.fandom.com/wiki/Dropping_Like_Flies
https://www.youtube.com/watch?v=5tm4dYla6Dg&ab_channel=mordof

Fixes:
Added lullaby resistance to houndfly
Added lullaby and sleep immunity to huntfly
Gave huntfly proper skillset (now includes sommersault) basis for this can be found in youtube video as well as wikipedia.

**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [ ] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [ ] I've _**tested my code and the things my code has changed**_ since the last commit in the PR, and will test after any later commits

## What does this pull request do?

## Steps to test these changes

2022-07-12 22:53 UTC, Mortalelite commented on scripts/zones/Horlais_Peak/mobs/Houndfly.lua
> +return entity
CI is warning you of this: All files need to end with a newline

2022-07-12 22:53 UTC, Mortalelite commented on scripts/zones/Horlais_Peak/mobs/Huntfly.lua
> +return entity
CI is warning you of this: All files need to end with a newline

2022-07-13 06:36 UTC, CriticalXI commented
Can you add the NO_STANDBACK mod to the main Huntfly? It should close into melee distance but doesn't because its set to BLM as a main job.

2022-07-15 08:26 UTC, zach2good approved these changes

2022-07-15 08:26 UTC, zach2good requested changes
I guess waiting on:

> Can you add the NO_STANDBACK mod to the main Huntfly? It should close into melee distance but doesn't because its set to BLM as a main job.

2022-07-15 15:10 UTC, zach2good approved these changes

2022-07-15 15:14 UTC, claywar approved these changes

2022-07-15 15:47 UTC, merged