[Lua] Implement remaining Geomantic Reservoirs
LandSandBoat/server pull request #2305
Opened 2022-07-17 00:11 UTC by CatsEyeXI

**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I've _**tested my code and the things my code has changed**_ since the last commit in the PR, and will test after any later commits

## What does this pull request do?
Implement remaining Geomantic Reservoirs.

ID's used:
https://github.com/zach2good/UpdateExtractor/tree/versions/2022-june/out/scripts/zones

## Steps to test these changes

Starting with a fresh character, add Indi-Spells, then visit corresponding Geomantic reservoir to unlock Geo-Spell.

2022-07-17 04:31 UTC, zach2good requested changes
Almost there 👍

2022-07-17 04:31 UTC, zach2good commented on scripts/zones/Batallia_Downs/npcs/Geomantic_Reservoir.lua
> +-- !pos -677.645 -32.000 157.981
All of these pos comments also need the zone number at the end so they can be traveled to from anywhere

2022-07-17 04:31 UTC, zach2good commented on scripts/zones/Beadeaux/IDs.lua
> +        LEARNS_SPELL                       = 7786, -- <name> learns <spell>!
These are out if order

2022-07-18 22:01 UTC, Omnione requested changes
Other than the oder, of a couple of text ID's, it looks good

2022-07-18 22:01 UTC, Omnione commented on scripts/zones/Sauromugue_Champaign/IDs.lua
> +        LEARNS_SPELL             = 12504, -- <name> learns <spell>!
These two need to be moved up to be in order

2022-07-19 20:36 UTC, Omnione requested changes
Once that comment in the header for Geo-Refresh is changed this will be good to go

2022-07-19 20:36 UTC, Omnione commented on scripts/zones/La_Theine_Plateau/npcs/Geomantic_Reservoir_2.lua
> +-- Unlocks: Geo-Regen
found a copy pasta, should be Geo-Refesh not Regen

2022-07-19 20:41 UTC, CatsEyeXI commented on scripts/zones/La_Theine_Plateau/npcs/Geomantic_Reservoir_2.lua
> +-- Unlocks: Geo-Regen
doh

2022-07-19 20:43 UTC, Omnione approved these changes

2022-07-19 20:47 UTC, Xaver-DaRed approved these changes

2022-07-21 05:29 UTC, zach2good approved these changes

2022-07-21 09:28 UTC, merged