Chocobo Circuit zone update from caps
LandSandBoat/server pull request #2316
Opened 2022-07-17 17:10 UTC by Tom-Neverwinter

**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I've _**tested my code and the things my code has changed**_ since the last commit in the PR, and will test after any later commits

## What does this pull request do?

adds the sql database entries missing from zone 70 Chocobo Circuit from cap files

## Steps to test these changes

run around the zone and confirm npcs are updated

2022-07-20 00:51 UTC, WinterSolstice8 requested changes

2022-07-20 00:51 UTC, WinterSolstice8 commented on sql/npc_list.sql
> +INSERT INTO `npc_list` VALUES (17064120,'Sigiswald','Sigiswald',199,-112.255,-11.500,-103.020,27,15,50,0,0,0,0,27,0x00005A0000000000000000000000000000000000,32,'TAOU',1);
find/replace
`TAOU` -> `TOAU`

2022-07-20 01:55 UTC, Tom-Neverwinter commented on sql/npc_list.sql
> +INSERT INTO `npc_list` VALUES (17064120,'Sigiswald','Sigiswald',199,-112.255,-11.500,-103.020,27,15,50,0,0,0,0,27,0x00005A0000000000000000000000000000000000,32,'TAOU',1);
Should be good, fixed another mistake I made as well

2022-07-23 23:00 UTC, WinterSolstice8 approved these changes
lgtm

2022-07-24 16:17 UTC, Xaver-DaRed commented on sql/npc_list.sql
> +INSERT INTO `npc_list` VALUES (17064138,'Gate:ChocoboC','Gate: Chocobo Circuit',0,-150.000,-2.000,-392.750,32769,50,50,0,0,0,0,3,0x0000340000000000000000000000000000000000,0,'TOAU',1);
`Gate:ChocoboC` is not a valid file name. Please chage it to ``GateChocoboC

2022-07-24 16:17 UTC, Xaver-DaRed commented on sql/npc_list.sql
> +INSERT INTO `npc_list` VALUES (17670612,'qm_bennu_3','???',0,80.000,0.250,-129.000,1,40,40,0,0,0,0,3,0x0000340000000000000000000000000000000000,0,'ABYSSEA',0);
This changes (Abyssea Altepa) shouldnt be here

2022-07-24 16:42 UTC, Tom-Neverwinter commented on sql/npc_list.sql
> +INSERT INTO `npc_list` VALUES (17670612,'qm_bennu_3','???',0,80.000,0.250,-129.000,1,40,40,0,0,0,0,3,0x0000340000000000000000000000000000000000,0,'ABYSSEA',0);
Fetch and merge resolves this. [maybe not] 

``I'll have to redownload npc list and manually edit it again then copy pasta zone 70``

https://raw.githubusercontent.com/LandSandBoat/server/base/sql/npc_list.sql

This insnt a change from my code. viewing the raw of the base its in there too. I only care about zone 70 in this one.

2022-07-24 16:53 UTC, Tom-Neverwinter commented on sql/npc_list.sql
> +INSERT INTO `npc_list` VALUES (17064138,'Gate:ChocoboC','Gate: Chocobo Circuit',0,-150.000,-2.000,-392.750,32769,50,50,0,0,0,0,3,0x0000340000000000000000000000000000000000,0,'TOAU',1);
Completed as requested

2022-07-25 10:56 UTC, Xaver-DaRed submitted a review, later dismissed
EDIT: Change what Claywar pointed out and this should be good to go.

2022-07-25 11:20 UTC, claywar commented on sql/npc_list.sql
> +INSERT INTO `npc_list` VALUES (17064153,'MandragoraAssi','Mandragora Assistant',192,-320.000,-0.850,-493.200,32782,50,50,0,0,32,0,1,0x00008F0B00000000000000000000000000000000,2,'NULL',1);
This is why CI is failing. Null Should not be in quotes

2022-07-26 09:21 UTC, claywar approved these changes

2022-07-26 09:22 UTC, merged