Circle ability revamp
LandSandBoat/server pull request #2334
Opened 2022-07-18 01:50 UTC by illzbee

**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I've _**tested my code and the things my code has changed**_ since the last commit in the PR, and will test after any later commits

## What does this pull request do?

Updates circle abilities recast time and subjob power to match retail

Closes: #634

2022-07-19 02:34 UTC, WinterSolstice8 requested changes

2022-07-19 02:34 UTC, WinterSolstice8 commented on scripts/globals/abilities/ancient_circle.lua
> -    xi.job_utils.dragoon.useAncientCircle(player, target, ability)
`xi.job_utils.dragoon.useAncientCircle` already handled the power. there was no need to change it. This is also a regression as it doesn't handle job points. Please revert this file.

2022-07-19 02:35 UTC, WinterSolstice8 commented
While you're editing these, could you add in the missing job point power checks?

see
`scripts\globals\job_utils\dragoon.lua` function `xi.job_utils.dragoon.useAncientCircle` for how that's done

2022-07-21 16:14 UTC, illzbee commented
> While you're editing these, could you add in the missing job point power checks?
> 
> see `scripts\globals\job_utils\dragoon.lua` function `xi.job_utils.dragoon.useAncientCircle` for how that's done

Added these in thanks for the tip to get it done!

2022-07-21 16:51 UTC, WinterSolstice8 commented
Hey so we didn't want the history of removing and re-adding the Ancient Circle file, so I rebased your commits to not have that. I squashed them so there's less commits as well to be cleaner. Your content was fine!

Git is difficult to use so you can reach out to us in discussion if you want to learn more about how to do those things.

2022-07-21 16:51 UTC, WinterSolstice8 approved these changes

2022-07-21 19:16 UTC, claywar approved these changes

2022-07-21 19:16 UTC, merged