[LUA] Update ID Shift to DYNAMIC_LOOKUP in Bhaflau Thickets
LandSandBoat/server pull request #2614
Opened 2022-08-29 16:28 UTC by HaxPrime

**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I've _**tested my code and the things my code has changed**_ since the last commit in the PR, and will test after any later commits

## What does this pull request do?

A recent retail update in Bhaflau Thickets shifted the ID's of two ZNM ID's. Setting these ID's to DYNAMIC_LOOKUP will help correct this shift. I used #2351 as a reference for my update.

## Steps to test these changes

Using `!spawnmob 16990473` to spawn Lividroot Amooshah returns an error for invalid mobid. Updating to dynamic lookup to bypass invalid mobid.

Using `!spawnmob 16990474` to spawn Dea returns an error for invalid mobid. Updating to dynamic lookup to bypass invalid mobid.

2022-08-30 09:09 UTC, claywar requested changes
Additional work needs to be done other than just changing those two definitions to dynamic.  In this case, any reference back needs to be updated as well.

```
-----------------------------------
-- Area: Bhaflau Thickets
--  NPC: ??? (Spawn Lividroot Amooshah(ZNM T2))
-- !pos 334 -10 184 52
-----------------------------------
local ID = require("scripts/zones/Bhaflau_Thickets/IDs")
require("scripts/globals/npc_util")
-----------------------------------
local entity = {}

entity.onTrade = function(player, npc, trade)
    if npcUtil.tradeHas(trade, 2578) and npcUtil.popFromQM(player, npc, ID.mob.LIVIDROOT_AMOOSHAH) then -- Trade Oily Blood
        player:confirmTrade()
        player:messageSpecial(ID.text.DRAWS_NEAR)
    end
end
```
The require in the above situation will return nil for `ID.mob.LIVIDROOT_AMOOSHAH` since it is not loading the updated copy of the IDs table, but rather the original in the zone.  This should instead use the zones[] table like:

`local ID = zones[xi.zone.BHAFLAU_THICKETS]`

2022-08-30 12:10 UTC, N3ckB3ard commented
> Additional work needs to be done other than just changing those two definitions to dynamic. In this case, any reference back needs to be updated as well.
> 
> ```
> -----------------------------------
> -- Area: Bhaflau Thickets
> --  NPC: ??? (Spawn Lividroot Amooshah(ZNM T2))
> -- !pos 334 -10 184 52
> -----------------------------------
> local ID = require("scripts/zones/Bhaflau_Thickets/IDs")
> require("scripts/globals/npc_util")
> -----------------------------------
> local entity = {}
> 
> entity.onTrade = function(player, npc, trade)
>     if npcUtil.tradeHas(trade, 2578) and npcUtil.popFromQM(player, npc, ID.mob.LIVIDROOT_AMOOSHAH) then -- Trade Oily Blood
>         player:confirmTrade()
>         player:messageSpecial(ID.text.DRAWS_NEAR)
>     end
> end
> ```
> 
> The require in the above situation will return nil for `ID.mob.LIVIDROOT_AMOOSHAH` since it is not loading the updated copy of the IDs table, but rather the original in the zone. This should instead use the zones[] table like:
> 
> `local ID = zones[xi.zone.BHAFLAU_THICKETS]`

Doing this kind of change will require the 

local ID = zones[xi.zone.BHAFLAU_THICKETS]

To be placed within each function to trigger correctly. This can be tested making direct changes to a lua and restarting the map server if you wish to have this local placed outside of the function and not called multiple times. I believe the purpose of this update is to currently create a module due to LSB standards of calling the local in every function that is pulling incorrect zone IDs.

As this issue has been pending for some time now related to the map log errors it would seem more efficient to update the IDs to dynamic and create modules to handle this. If you have a solution to fix this I can assure you the current method of initiation of that local fails outside of a function. We reference the IDs lua twice per ZNM

2022-08-30 12:20 UTC, N3ckB3ard commented
> 

Unless you mean entirely removing 
local ID = require("scripts/zones/Bhaflau_Thickets/IDs")

And replacing this with
local ID = zones[xi.zone.BHAFLAU_THICKETS]

In 2351 this adjustment was not made to the direct luas of the ZNM's so having a reference or understanding of this will help support future use of this modification to the LUA files. A PR can also be made to fix Arrapago Reef as these are also missing this local.

2022-08-30 12:45 UTC, claywar commented
You will need to replace those variable definitions in any scripts that currently use those mobs that are now dynamically looked up.  I believe theres two scripts currently, one that I posted above.

2022-08-30 15:58 UTC, N3ckB3ard commented
> You will need to replace those variable definitions in any scripts that currently use those mobs that are now dynamically looked up. I believe theres two scripts currently, one that I posted above.

![unknown-18](https://user-images.githubusercontent.com/98081508/187482340-da9f848e-9458-4b24-868a-ade1f7c0a13b.png)

qm2.lua 
```lua
-----------------------------------
-- Area: Bhaflau Thickets
--  NPC: ??? (Spawn Dea(ZNM T3))
-- !pos -34 -32 481 52
-----------------------------------
local ID = zones[xi.zone.BHAFLAU_THICKETS]
require("scripts/globals/npc_util")
-----------------------------------
local entity = {}

entity.onTrade = function(player, npc, trade)
    if npcUtil.tradeHas(trade, 2576) and npcUtil.popFromQM(player, npc, ID.mob.DEA) then -- Trade Olzhiryan Cactus
        player:confirmTrade()
        player:messageSpecial(ID.text.DRAWS_NEAR)
    end
end

entity.onTrigger = function(player, npc)
    player:messageSpecial(ID.text.SHED_LEAVES)
end

entity.onEventUpdate = function(player, csid, option)
end

entity.onEventFinish = function(player, csid, option)
end

return entity
```

It seems this error is persistent on reboot. If file watcher sees a modification to this LUA it will then correct the ZoneID. Could this potentially be a initialize related problem? I do know placing the local within the entity.onTrade = function will fix this and work on reboot.

2022-08-30 16:20 UTC, EpicTaru commented
Isn't the better resolution to find the new MobIDs of those that shifted and just update the IDs.la file with those new MobIDs? Just trying to understand why we're converting mobs to DYNAMIC_LOOKUPS.

2022-08-30 17:46 UTC, claywar commented
> It seems this error is persistent on reboot. If file watcher sees a modification to this LUA it will then correct the ZoneID. Could this potentially be a initialize related problem? I do know placing the local within the entity.onTrade = function will fix this and work on reboot.

Try requiring 'scripts/globals/zones' prior to the ID definition, not sure of the load order.

2022-08-30 17:47 UTC, claywar commented
> Isn't the better resolution to find the new MobIDs of those that shifted and just update the IDs.la file with those new MobIDs? Just trying to understand why we're converting mobs to DYNAMIC_LOOKUPS.

This is a do it once and never have to deal with it again operation, as opposed to having to search through all of those lua files each month (and no current automation in place to do it).  Its a small up front cost to converting to save headaches in the future.

2022-08-30 18:00 UTC, EpicTaru commented
> This is a do it once and never have to deal with it again operation, as opposed to having to search through all of those lua files each month (and no current automation in place to do it). Its a small up front cost to converting to save headaches in the future.

Gotcha, understood, thanks for the clarification, Claywar. 👍🏼

2022-09-03 15:25 UTC, claywar approved these changes

2022-09-03 15:26 UTC, merged