Beitetsu Parcel, items_usable and .lua to function
LandSandBoat/server pull request #2677
Opened 2022-09-08 05:46 UTC by apatrickm

**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I've _**tested my code and the things my code has changed**_ since the last commit in the PR, and will test after any later commits

## What does this pull request do?
Adds the Beitetsu Parcel to items_usable, and adds beitetsu_parcel.lua to add Beitetsu same as retail

## Steps to test these changes
Use a beitetsu parcel

2022-09-08 05:48 UTC, WinterSolstice8 requested changes

2022-09-08 05:48 UTC, WinterSolstice8 commented on sql/item_usable.sql
> +INSERT INTO `item_usable` VALUES (6181,'Beitetsu_Parcel',1,1,24,0,0,0,0,0);
lowercase please

2022-09-08 05:48 UTC, WinterSolstice8 commented on scripts/globals/items/beitetsu_parcel.lua
> +return item_object
no newline at end of file

2022-09-08 09:12 UTC, zach2good commented on scripts/globals/items/beitetsu_parcel.lua
> +    target:addItem(4060, math.random(3, 15))
Please don't use a magic number here, add an entry in `items.lua`, add the relevant require to the top of this file, and replace the magic number with `xi.items.BEITETSU`

2022-09-08 09:14 UTC, zach2good commented on scripts/globals/items/beitetsu_parcel.lua
> +
From CI:
```
scripts/globals/items/beitetsu_parcel.lua:23: Found multiple newline characters next to each other, please replace these with single newlines.
```

2022-09-08 09:34 UTC, zach2good commented on scripts/globals/items/beitetsu_parcel.lua
> +
You had it correct in this commit: https://github.com/LandSandBoat/server/pull/2677/commits/f29ac19fcaebbde2066f3cf7f5ab262e15fe0c0c

2022-09-09 06:34 UTC, zach2good requested changes

2022-09-09 06:34 UTC, zach2good commented on scripts/globals/items/beitetsu_parcel.lua
> +-----------------------------------
```suggestion
require('scripts/globals/items')
require("scripts/globals/msg")
-----------------------------------
```

2022-09-09 06:34 UTC, zach2good commented on scripts/globals/items/beitetsu_parcel.lua
> +    target:addItem(xi.items.BEITETSU, math.random(3, 15))
`xi.items.BEITETSU` doesn't exist in `scripts/globals/items.lua`, you need to add this line to it:
```lua
    BEITETSU                        = 4060,
```

2022-09-09 06:34 UTC, zach2good commented on scripts/globals/items/beitetsu_parcel.lua
> +    target:addItem(xi.items.BEITETSU, math.random(3, 15))
While you're there, you can also add an entry for `BEITETSU_PARCEL` (id 6181)

2022-09-24 01:42 UTC, WinterSolstice8 requested changes

2022-09-24 01:42 UTC, WinterSolstice8 commented on scroll_of_arise.lua
> +    return target:canLearnSpell(494)
494 -> xi.magic.spell.ARISE

2022-09-24 01:42 UTC, WinterSolstice8 commented on scroll_of_inundation.lua
> +    return target:canLearnSpell(879)
879 -> xi.magic.spell.INUNDATION

2022-09-25 21:54 UTC, WinterSolstice8 approved these changes
LGTM though needs merge conflict fixed

2022-09-27 12:52 UTC, zach2good commented
These are not relevant to this PR and should be removed:
- scroll_of_arise.lua
- scroll_of_inundation.lua

2022-09-27 21:36 UTC, apatrickm commented
The other 2 scroll lua's were added because I can only put in 1 request at a time

2022-09-28 07:55 UTC, zach2good commented
Replacing this PR with https://github.com/LandSandBoat/server/pull/2819, https://github.com/LandSandBoat/server/pull/2821, and https://github.com/LandSandBoat/server/pull/2820

2022-09-28 07:55 UTC, closed without merging

2022-09-28 07:57 UTC, zach2good commented
In future, please look up how to use git and GitHub from your desktop, not the web client, and how to squash your commits together (or rebase, if you're feeling brave)