[LUA] Create job_utils/dark_knight and audit JA functionality
LandSandBoat/server pull request #2877
Opened 2022-10-04 08:13 UTC by Schaedelschaden

**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I've _**tested my code and the things my code has changed**_ since the last commit in the PR, and will test after any later commits

## What does this pull request do?

**Job Abilities**
- Create job_utils/dark_knight.lua and populates necessary ability check and ability use functions.
- Moves functionality from all Dark Knight globals/abilities files to globals/job_utils/dark_knight.lua.

**Effects**

**Spells**

**Core/LUA Functions**

**NOTE:** These lists will be updated as progress is made on the PR.

## References

## Steps to test these changes

1. Upload changes to your server.
2. Load the server.
3. Use the `!changejob DRK 99` command.
4. Use all JA's to confirm they do not throw errors.
5. Test all JA's and compare their behavior to BGWiki JA descriptions.

2022-11-03 10:46 UTC, Xaver-DaRed commented on scripts/globals/spells/absorb_spell.lua
> +    if (target:getMP() > aspir) then
Sorry for the late review.

unneeded parenthesys here

2022-11-03 10:52 UTC, Xaver-DaRed commented on scripts/globals/spells/damage_spell.lua
> +    spellDamage = spellDamage * xi.spells.damage.calculateScarletDeliriumMultiplier(caster)
This should be handled where all multipliers to base damage are handled.
That is in the very last function of this file.

2022-11-03 10:57 UTC, Xaver-DaRed commented
This is a lot to take in, tbh.

I would recomend separating it into smaller and more managable PRs to ease both reviewing and testing.

2022-11-03 11:00 UTC, Xaver-DaRed commented
I apreciate the work done to spells.

Having said that though, one of the main objectives with the spell rewrite was to use as few/none external functions as possible. Making it self-contained and more importantly, more retail-like.

Specially important with status effect resistance handling and such. We know we currently do not do it correctly and I would personally ratherrewrite the resistance calculations first before any work goes into them.

2022-11-03 11:32 UTC, TeoTwawki requested changes
this should be broken apart into multiple separate pull requests - it's too large

2022-11-03 11:47 UTC, Schaedelschaden commented
I was worried this got too big as I went through all of the JA's :( Now that I have everything laid out I can split it into much more manageable PR's. Any recommendations on what a good split would be?

2022-11-03 11:51 UTC, Xaver-DaRed commented
I would first thing divide spell from ability job.

You could start by moving existing logic out of abilities into its job utils and then add the modifiers. in small chuncks.

As for spell work, I would rather do that myself, so I can work on resistance calculations first.

2022-11-03 11:53 UTC, TeoTwawki commented
> I was worried this got too big as I went through all of the JA's :( Now that I have everything laid out I can split it into much more manageable PR's. Any recommendations on what a good split would be?

Maybe get a basic skeleton in, start porting one new modifier at a time with its matching spell/job ability so reviewers can focus on the code related to that mod

2022-11-03 11:56 UTC, TeoTwawki commented
doesn't have to exactly be broken down that far, but the more broken down it is the faster each piece gets in

2023-01-13 16:09 UTC, Xaver-DaRed commented
Slowly importing changes from this PR, in small, easily reviewable chunks.
Sorry it has taken so long

2023-01-13 18:04 UTC, Schaedelschaden commented
Thank you for the work @Xaver-DaRed. I apologize for dropping this and disappearing, my daughter’s premature birth and trying to get everything handled for her took me away and haven’t given me any time to get back to this. I hope that starting next week I should be able to start catching up on things and return to working on these job audits (in more manageable chunks).

2024-08-09 10:45 UTC, Xaver-DaRed commented
Most of the changes here have already been imported, in smaller chunks. Only things missing are the absorb spells, from a quick glance and my own memory.

I will get to those soon. But for the time being, this can be closed. TY a lot for this contribution.

2024-08-09 10:45 UTC, closed without merging