Interaction Quest Soothing Waters
LandSandBoat/server pull request #2900
Opened 2022-10-07 03:22 UTC by KnowOne134

**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I've _**tested my code and the things my code has changed**_ since the last commit in the PR, and will test after any later commits

## What does this pull request do?

Adds missing quest Soothing Waters to Interaction

2022-10-07 03:29 UTC, WinterSolstice8 requested changes

2022-10-07 03:29 UTC, WinterSolstice8 commented on scripts/quests/ahtUrhgan/Soothing_Waters.lua
> +                onTringger = function(player, npc)
typo here `onTrigger`

2022-10-08 23:13 UTC, KnowOne134 commented on scripts/quests/ahtUrhgan/Soothing_Waters.lua
> +                onTringger = function(player, npc)
got it, good catch ty

2022-10-10 01:25 UTC, WinterSolstice8 approved these changes

2022-10-12 01:07 UTC, merged