[Nyzul] Change raw Ids to GetFirstID() and fix some npcs not loading
LandSandBoat/server pull request #3420
Opened 2022-12-21 12:32 UTC by Xaver-DaRed

**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my PR will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have _**tested my code and the things my code has changed**_ since the last commit in the PR and will test after any later commits.

## What does this pull request do?

 - Changes some raw IDs to use GetFirstID()
 - Changed some NPCs pos values to be "not 0" so they actually load
 - Changed RUNIC_LAMP_1 name to RUNIC_LAMP_OFFSET and removed unused npc definitions in IDs file

## Steps to test these changes

? Nyzul is disabled

2022-12-21 12:46 UTC, claywar approved these changes

2022-12-21 12:49 UTC, zach2good requested changes

2022-12-21 12:49 UTC, zach2good commented on scripts/zones/Nyzul_Isle/IDs.lua
> +            GetFirstID("Armoury_Crate"), GetFirstID("Armoury_Crate") + 1, GetFirstID("Armoury_Crate") + 4, GetFirstID("Armoury_Crate") + 11
I'm not certain this will work;

https://github.com/LandSandBoat/server/blob/base/src/map/lua/luautils.cpp#L790

We don't iterate down multiple levels of the npc and mob tables in here, only the base level

2022-12-21 12:53 UTC, Xaver-DaRed commented on scripts/zones/Nyzul_Isle/IDs.lua
> +            GetFirstID("Armoury_Crate"), GetFirstID("Armoury_Crate") + 1, GetFirstID("Armoury_Crate") + 4, GetFirstID("Armoury_Crate") + 11
I dont see why it wouldnt.  GetFirstID() returns a numeric value, to which I add a number. Or do you mean we cant have math in here?

2022-12-21 13:10 UTC, Xaver-DaRed commented on scripts/zones/Nyzul_Isle/IDs.lua
> +            GetFirstID("Armoury_Crate"), GetFirstID("Armoury_Crate") + 1, GetFirstID("Armoury_Crate") + 4, GetFirstID("Armoury_Crate") + 11
For now, reverted that set of changes

2022-12-22 15:11 UTC, zach2good approved these changes

2022-12-22 15:14 UTC, merged