Campaign teleport/retrace behavior
LandSandBoat/server pull request #4721
Opened 2023-11-12 03:57 UTC by MowFord

**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my PR will be ignored.
- [x] I understand I should leave resolving conversations to the LandSandBoat team so that reviewers won't miss what was said.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have _**tested my code and the things my code has changed**_ since the last commit in the PR and will test after any later commits.

## What does this pull request do?

Updated `campaign.lua` to support two new sets of functions for teleporting from nations to the campaign front and retracing from the campaign front to the aligned nation.

Only the former is implemented in npc lua files, but the latter is confirmed to work via 

```
-----------------------------------
-- Type: Campaign Arbiter
-- !pos TODO
-----------------------------------
require("scripts/globals/campaign")
-----------------------------------
local campaignEvent = 457
local entity = {}

entity.onTrade = function(player, npc, trade)
end

entity.onTrigger = function(player, npc)
    xi.campaign.campaignArbiterOnTrigger(player, npc, campaignEvent)
end

entity.onEventUpdate = function(player, csid, option)
    xi.campaign.campaignArbiterOnEventUpdate(player, csid, option, campaignEvent)
end

entity.onEventFinish = function(player, csid, option)
    xi.campaign.campaignArbiterOnEventFinish(player, csid, option, campaignEvent)
end

return entity
```

Regardless, the teleportation confirms having visiting the zones, then pushed the menu based on that.

Sidenote: there's an issue with the default action on the npc `Scarlette_CA` that really got me hung up and delayed my progress here... putting in a separate PR for it to also discuss what the dealio is with it.

![image](https://github.com/LandSandBoat/server/assets/131182600/169ada2d-08f6-476e-98e1-6c85ac896cae)

The menu didn't show CN_S until i zoned to CN_S and went back to npc

## Steps to test these changes

Interact with the CA NPCs in the 3 nations in the past and get the default "Civilian what are you doing" message. Adjust your allegiance and get the menu based on zones visited (with a catchall if somehow you end up in the past nation, with an allegiance, and never having visited the zones)

2023-11-26 13:57 UTC, Xaver-DaRed approved these changes
Please add the positions to the npcs.

2023-12-23 07:20 UTC, Xaver-DaRed commented
This needs a rebase to resolve conflicts.

2023-12-23 12:45 UTC, MowFord commented
> This needs a rebase to resolve conflicts.

Thanks for lookin out. All clear now

2024-01-27 20:00 UTC, claywar requested changes

2024-01-27 20:00 UTC, claywar commented on scripts/zones/Southern_San_dOria_[S]/DefaultActions.lua
> -    ['Saphiriance_TK']           = { event = 450 },
Why are these being removed? These are absolutely valid from caps when unavailable, which would be prior to access from quests.  These _are_ the default action.

2024-01-28 17:08 UTC, MowFord commented on scripts/zones/Southern_San_dOria_[S]/DefaultActions.lua
> -    ['Saphiriance_TK']           = { event = 450 },
The updated npc lua handles this event when the player doesn't have campaign allegiance

2024-01-28 17:35 UTC, claywar commented on scripts/zones/Southern_San_dOria_[S]/DefaultActions.lua
> -    ['Saphiriance_TK']           = { event = 450 },
I may be misunderstanding, but you seem to be using base event of 458 - 1 for no allegiance.  This is a global, and I would suggest testing this with other zones.

2024-04-28 22:16 UTC, MowFord commented on scripts/zones/Southern_San_dOria_[S]/DefaultActions.lua
> -    ['Saphiriance_TK']           = { event = 450 },
Saphiriance was flagged in this request but the question about 458 - 1 was about a different npc.

I see now that there was a mistake and it should be +1 for no allegiance:

![image](https://github.com/LandSandBoat/server/assets/131182600/879ed9db-d503-4ecb-a2ae-2c9120d58d13)

I've rebased, then made that adjustment and tested the NPCs with and without allegiance

2024-05-31 01:33 UTC, closed without merging