Further implement Trust: Zied II
LandSandBoat/server pull request #4925
Opened 2023-12-29 03:46 UTC by CatsEyeXI

**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my PR will be ignored.
- [x] I understand I should leave resolving conversations to the LandSandBoat team so that reviewers won't miss what was said.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have _**tested my code and the things my code has changed**_ since the last commit in the PR and will test after any later commits.

## What does this pull request do?
Builds off of the implementation of Zied II to add missing mob skills.
I need some feedback regarding the gambit creation for Absorb-Attri (#4921)
Typically this appears to be handled using `NOT_STATUS`, but in this case we'd need to check for many?
Do we define a set somehow? 

## Steps to test these changes
![image](https://github.com/LandSandBoat/server/assets/65316697/bfa54ca3-cad0-4b9a-9964-108ac446cee5)
![image](https://github.com/LandSandBoat/server/assets/65316697/3ba0c177-79ac-4b89-9867-ebf817e4653b)
![image](https://github.com/LandSandBoat/server/assets/65316697/58e87b3f-a69d-4d8c-ade3-d14036037c82)

2023-12-29 04:05 UTC, TeoTwawki commented
"Zied" 
![image](https://github.com/LandSandBoat/server/assets/6871475/14d6c867-ea25-4290-ba91-319448928efb)

2023-12-29 04:26 UTC, CatsEyeXI commented
> "Zied" ![image](https://private-user-images.githubusercontent.com/6871475/293307864-14d6c867-ea25-4290-ba91-319448928efb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM4MjQyNzQsIm5iZiI6MTcwMzgyMzk3NCwicGF0aCI6Ii82ODcxNDc1LzI5MzMwNzg2NC0xNGQ2Yzg2Ny1lYTI1LTQyOTAtYmE5MS0zMTk0NDg5MjhlZmIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDIzMTIyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjlUMDQyNjE0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDRlNDk2ZDIxMGQwNjg3MDFiYmI5OTY5OWFlNmIzYzgxMzg0OWM2NjNmOWRmYTViNzEyN2U5MzcyYjliZGM0YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.JD_1_9xVI8LBxyJP6jE5uOccYnHWbAkpdoaK8VxW6vw)

even fixed the skill list name :)

2023-12-29 09:21 UTC, zach2good requested changes
Zeid II already handles souleater and last resort as JAs: https://github.com/LandSandBoat/server/blob/base/scripts/actions/spells/trust/zeid_ii.lua#L30-L35

Did you see something in packets to indicate that these are executed as mobskills? Or does he fire these off as weaponskills/mobskills in addition to ground strike on retail?

By setting them as weaponskills, (I think?) he might dump TP to try and use them? This looks mighty fishy

2023-12-29 09:21 UTC, zach2good commented on scripts/actions/spells/trust/zeid_ii.lua
> +        [xi.magic.spell.LION_II] = xi.trust.messageOffset.TEAMWORK_1,
Huh, I would have thought he had more than just Lion. Get someone to check if he also does a modified line for LION_I and not just LION_II.

What do his message dumps say?

2023-12-29 09:21 UTC, zach2good commented on sql/mob_skill_lists.sql
> +INSERT INTO `mob_skill_lists` VALUES ('TRUST_Zeid_II',1125,710); -- Souleater
These are abilities, not weaponskills/mobskills?

2023-12-29 09:27 UTC, zach2good commented on scripts/actions/spells/trust/zeid_ii.lua
> +        [xi.magic.spell.LION_II] = xi.trust.messageOffset.TEAMWORK_1,
(My local builds are playing up at the moment, I can't dump them for you like I did for Lion I and II)

2023-12-29 12:50 UTC, CatsEyeXI commented
Hi Zach. It's a good point and I'll check.

2023-12-29 14:26 UTC, zach2good commented
Zeid I's pages:
<img width="283" alt="image" src="https://github.com/LandSandBoat/server/assets/1389729/e4a846de-0cb0-4fb3-ad6f-b497b406f53c">

Zeid II's pages:
<img width="299" alt="image" src="https://github.com/LandSandBoat/server/assets/1389729/704149c9-094f-466f-90e9-3f5dc02c6bbd">

Zeid II also has another section towards the bottom which I _suspect_ are response lines, or used during a skillchain, or in response to other trusts being summoned: but we don't have plumbing for those yet so you can disregard

2023-12-29 14:27 UTC, zach2good commented
These are directly related to:
```lua
xi.trust.messageOffset =
{
    SPAWN          = 1,
    TEAMWORK_1     = 4,
    TEAMWORK_2     = 5,
    TEAMWORK_3     = 6,
    TEAMWORK_4     = 7,
    TEAMWORK_5     = 8,
    DEATH          = 9,
    DESPAWN        = 11,
    SPECIAL_MOVE_1 = 18,
    SPECIAL_MOVE_2 = 19,
}

```

2023-12-29 14:36 UTC, zach2good commented on scripts/actions/spells/trust/zeid_ii.lua
> +        [xi.magic.spell.LION_II] = xi.trust.messageOffset.TEAMWORK_1,
Confirmed: Zeid II only responds to Lion II, not Lion I

2023-12-29 16:03 UTC, CatsEyeXI commented on sql/mob_skill_lists.sql
> +INSERT INTO `mob_skill_lists` VALUES ('TRUST_Zeid_II',1125,710); -- Souleater
you are right, they are abilities and not mob skills that would consume TP. I've removed that from the PR.

2023-12-29 16:07 UTC, zach2good commented on scripts/actions/spells/trust/zeid_ii.lua
> +        [xi.magic.spell.LION_II] = xi.trust.messageOffset.TEAMWORK_1,
xi.trust.teamworkMessage replaces xi.trust.message(, otherwise you're going to get 2x spawn messages.

2023-12-29 17:08 UTC, WinterSolstice8 commented
Zeid II says "Never again will I lose sight of who I am" on use of ground strike

2023-12-29 21:06 UTC, CatsEyeXI commented
> Zeid II says "Never again will I lose sight of who I am" on use of ground strike

![image](https://github.com/LandSandBoat/server/assets/65316697/ca0bb570-7c38-4a8a-8e73-32fd83290066)

2023-12-30 09:24 UTC, zach2good commented
This looks ready to go, it just needs squashing (we can do that) and https://github.com/LandSandBoat/server/pull/4921 to merge

2024-01-03 09:34 UTC, zach2good approved these changes

2024-01-03 09:35 UTC, merged