[cpp] Immanence logic cleanup
LandSandBoat/server pull request #5525
Opened 2024-04-26 04:35 UTC by MowFord

**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my PR will be ignored.
- [x] I understand I should leave resolving conversations to the LandSandBoat team so that reviewers won't miss what was said.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have _**tested my code and the things my code has changed**_ since the last commit in the PR and will test after any later commits.

## What does this pull request do?

Simple fix to Immanence JA not being usable if already have the effect and giving a message that the effect wears off when casting a spell (just like all other stratagems)

Meat of the PR:
- Someone reported helixes weren't skillchaining or consuming the effect. I believe they dealing zero damage and correctly not applying skillchain effect. This is a common retail tactic
- magic numbers and duplicate calls to `GetSkillChainEffect` bothered me enough to refactor it
- Also made me read up a bit more and found that closing a skillchain with a helix boosts the skillchain effect duration by 2s

## Steps to test these changes

![image](https://github.com/LandSandBoat/server/assets/131182600/dbdfefe9-4a8b-4d98-8e78-19a92ef7f2f9)

I added a print to `effects/skillchain.lua` on effect gain and lose. first start/end was a simple nuke, second group was closing a skillchain with a helix:
![image](https://github.com/LandSandBoat/server/assets/131182600/5a284aa8-d17e-4c92-8abd-610729f6c797)

![image](https://github.com/LandSandBoat/server/assets/131182600/8929f16e-744f-450c-a24a-c0612b7a3ba0)

2024-04-26 04:41 UTC, MowFord commented
Final testing after last commit: 
![image](https://github.com/LandSandBoat/server/assets/131182600/47e19b7d-79eb-4597-aab5-282193022ac7)

2024-04-26 16:25 UTC, MowFord commented
do i need to put explicit `[[fallthrough]];` on each?

2024-04-27 18:35 UTC, WinterSolstice8 approved these changes
I feel like the case/switch could be simplified, but it does the job

2024-04-27 18:36 UTC, WinterSolstice8 requested changes

2024-04-27 18:36 UTC, WinterSolstice8 commented on src/map/entities/charentity.cpp
> +                        scEffect->SetDuration(12000);
Second thought: should this not get the duration then add 2000? Skillchains are supposed to have reduced duration at least for follow skillchains.

2024-05-13 16:16 UTC, closed without merging