[Module] Create module for quest workarounds
LandSandBoat/server pull request #5831
Opened 2024-05-24 19:48 UTC by hooksta4

**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my PR will be ignored.
- [x] I understand I should leave resolving conversations to the LandSandBoat team so that reviewers won't miss what was said.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have _**tested my code and the things my code has changed**_ since the last commit in the PR and will test after any later commits.

## What does this pull request do?
Allows players to complete the quest Wish Upon a Star. Currently, Bastok does not have a "NONE" weather and therefore will never take the fallen star item. Adding sunshine (clear) remediates this.

Adds an or player:getWeather() == xi.weather.SUNSHINE
## Steps to test these changes
Run through the quest players will now be able to complete the quest.

2024-05-26 12:32 UTC, zach2good approved these changes

2024-05-26 12:32 UTC, zach2good commented
Would the right thing to do here be to give Bastok `NONE` weather?

2024-05-26 12:34 UTC, zach2good requested changes
This is a workaround, not a fix

2024-05-26 12:34 UTC, zach2good commented
Looking at my weather tracker on retail:
<img width="332" alt="image" src="https://github.com/LandSandBoat/server/assets/1389729/5646b17f-6735-49f6-a654-ec40f0112313">

2024-05-26 12:42 UTC, hooksta4 commented
> Would the right thing to do here be to give Bastok `NONE` weather?

Yes, that would be the correct fix.

2024-05-26 12:45 UTC, zach2good commented
<img width="756" alt="image" src="https://github.com/LandSandBoat/server/assets/1389729/695ffab0-1ae4-41a6-b8db-ee388f322ef9">

2024-05-26 12:47 UTC, zach2good commented
[db.zip](https://github.com/LandSandBoat/server/files/15447488/db.zip)

Here is my current sqlite db for the weather reporter, there should be enough information in there to get you started, plus the query in the SS above. 

zone.cpp explains in great detail how to set up weather information for zones:
```cpp

/*************************************************************************
 *                                                                        *
 *  Loads weather for the zone from zone_bweather SQL Table               *
 *                                                                        *
 *  Weather is a rotating pattern of 2160 vanadiel days for each zone.    *
 *  It's stored as a blob of 2160 16-bit values, each representing 1 day  *
 *  starting from day 0 and storing 3 5-bit weather values each.          *
 *                                                                        *
 *              0        00000       00000        00000                   *
 *              ^        ^^^^^       ^^^^^        ^^^^^                   *
 *          padding      normal      common       rare                    *
 *                                                                        *
 *************************************************************************/

void CZone::LoadZoneWeather()
{
    TracyZoneScoped;
    static const char* Query = "SELECT weather FROM zone_weather WHERE zone = %u";

```

2024-05-26 12:48 UTC, zach2good commented
Reason I won't accept this ([as I explained once in a stream](https://www.twitch.tv/videos/1904611177)) is that if this goes in, it'll never be properly fixed because it's so small an innocuous. All the information to do it properly is available.

2024-05-26 12:58 UTC, hooksta4 commented
That's fair.

2024-05-26 13:23 UTC, zach2good commented
If you're not able to do the weather data breakdown, you can change this PR to provide a 'workarounds' Lua module that changes this condition using [xi.module.modifyInteractionEntry](https://github.com/LandSandBoat/server/blob/base/modules/module_utils.lua#L24), which will be off by default.

2024-05-26 13:23 UTC, zach2good commented
In that module, you can provide the steps needed to remedy and get rid of the workaround

2024-05-27 00:45 UTC, hooksta4 commented
@zach2good  - tested this out good to go. Reverted the original file back to what it is currently.

2024-05-27 11:47 UTC, zach2good reviewed
Almost there

2024-05-27 11:47 UTC, zach2good commented on modules/era/lua/wish_upon_a_star.lua
> +-- Using "Sunny" weather instead.
Use the _original_ "fix" you proposed by using both NONE and SUNSHINE.

2024-05-27 11:47 UTC, zach2good commented on modules/era/lua/wish_upon_a_star.lua
> +-----------------------------------
Move this whole thing to a `quest_workarounds` module, where `xi.module.modifyInteractionEntry('scripts/quests/bastok/Wish_Upon_a_Star', function(quest)` is just a single part of it, with the comments above it.

```
m:addOverride('xi.server.onServerStart', function()
    super()

-- Module to make Wish Upon a Star completable.
-- TODO include NONE in weather for bastok markets.
-- https://github.com/LandSandBoat/server/pull/5831 comments for fix action
-- Currently, Bastok does not have a "NONE" weather
-- Therefore, the quest cannot be completed.
-- Using this module, will allow the quest to be completed
-- Using "Sunny" weather instead.
    xi.module.modifyInteractionEntry('scripts/quests/bastok/Wish_Upon_a_Star', function(quest)
        quest.sections[2][xi.zone.BASTOK_MARKETS]['Enu'].onTrade = function(player, npc, trade)
        local isNight = VanadielTOTD() == xi.time.NIGHT or VanadielTOTD() == xi.time.MIDNIGHT
            if npcUtil.tradeHasExactly(trade, xi.item.FALLEN_STAR) then
                if
                    player:getWeather() == xi.weather.SUNSHINE and
                    isNight
                then
                    return quest:progressEvent(334)
                else
                    return quest:event(337)
                end
            end
        end
    end)
end)
```

Something like this, but formatted correctly, etc.

We don't want an explosion of modules for no reason

2024-05-27 11:47 UTC, zach2good commented on modules/era/lua/wish_upon_a_star.lua
> +        local isNight = VanadielTOTD() == xi.time.NIGHT or VanadielTOTD() == xi.time.MIDNIGHT
Missing an indent level here

2024-05-29 21:17 UTC, zach2good commented on modules/era/lua/quest_workarounds.lua
> +end) -- End of all modules
These comments aren't really needed, if people want additional clarity they can just pull out a function.

2024-05-29 21:17 UTC, zach2good commented on modules/era/lua/quest_workarounds.lua
> +-----------------------------------
This whole section is overkill.

You only need to say at the lines below:
```lua
-- Bastok zones don't currently produce NONE weather, so we are adding SUNSHINE as an accepted weather so the quest becomes completable.
-- See: https://github.com/LandSandBoat/server/pull/5831
xi.module.modifyInteractionEntry('scripts/quests/bastok/Wish_Upon_a_Star', function(quest)
```
```

2024-05-29 21:17 UTC, zach2good commented on modules/era/lua/quest_workarounds.lua
> +-- This module is intended to be a complilation
complilation -> compilation

2024-05-29 21:17 UTC, zach2good commented on modules/era/lua/quest_workarounds.lua
> +-- larger (like a system) that has not been impliemented
impliemented -> implemented

2024-05-29 21:37 UTC, hooksta4 commented on modules/era/lua/quest_workarounds.lua
> +-----------------------------------
Done.

2024-05-29 22:36 UTC, zach2good commented on modules/era/lua/quest_workarounds.lua
> +-----------------------------------
```lua
-- Bastok zones don't currently produce NONE weather, so we are adding SUNSHINE as an accepted weather so the quest becomes completable.
-- See: https://github.com/LandSandBoat/server/pull/5831
xi.module.modifyInteractionEntry('scripts/quests/bastok/Wish_Upon_a_Star', function(quest)
```

^ As shown, I meant for you to put it above the code

2024-08-04 08:17 UTC, zach2good commented
Please don't resolve conversation threads on your own, you've checked this box:
```
 I understand I should leave resolving conversations to the LandSandBoat team so that reviewers won't miss what was said.
```

It's there to make reviewers lives easier.

2024-08-04 08:18 UTC, zach2good approved these changes

2024-08-04 08:19 UTC, zach2good commented
`modules/era/lua/quest_workarounds.lua`

This doesn't have anything to do with a specific era, I'm going to pull this down into a different branch and `git mv` it, and submit it in a new PR (attribution preserved, obviously)

2024-08-05 09:06 UTC, merged