[Quest]WHM AF1 MSG'r From Beyond
LandSandBoat/server pull request #5849
Opened 2024-05-29 21:14 UTC by hooksta4

**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my PR will be ignored.
- [x] I understand I should leave resolving conversations to the LandSandBoat team so that reviewers won't miss what was said.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have _**tested my code and the things my code has changed**_ since the last commit in the PR and will test after any later commits.

## What does this pull request do?
Converts WHM AF1 to IF. 
- Removes logic from NPC files.
- Adds a dialog when spawning NM.

## Steps to test these changes
Be on whm 40+ Speak with Narchera
Pop and Kill NM 
Return Tavnazia Pass to Narchera

2024-06-16 15:31 UTC, claywar requested changes
Overall fairly reasonable, but removing the default and attaching it to a quest is not acceptable.  This must be changed.

2024-06-16 15:31 UTC, claywar commented on scripts/quests/sandoria/WHM_AF1_Messenger_From_Beyond.lua
> +local valkID = zones[xi.zone.VALKURM_DUNES]
Lets not abbreviate more than necessary, `valkurmID`

2024-06-16 15:31 UTC, claywar commented on scripts/quests/sandoria/WHM_AF1_Messenger_From_Beyond.lua
> +                        return quest:messageSpecial(valkID.text.NOTHING_OUT_OF_ORDINARY)
This should be in DefaultActions

2024-06-16 15:31 UTC, claywar commented on scripts/quests/sandoria/WHM_AF1_Messenger_From_Beyond.lua
> +                    return quest:event(688)
This is not relevant to this quest, and is either a default action or should remain in his script

2024-06-19 15:19 UTC, hooksta4 commented on scripts/quests/sandoria/WHM_AF1_Messenger_From_Beyond.lua
> +                    return quest:event(688)
made changes to all.. Thanks!

2024-09-04 11:42 UTC, closed without merging