[sql] Add Gigas Bracelets Desynth
LandSandBoat/server pull request #5996
Opened 2024-07-12 00:54 UTC by 9001-Sols

**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my PR will be ignored.
- [x] I understand I should leave resolving conversations to the LandSandBoat team so that reviewers won't miss what was said.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have _**tested my code and the things my code has changed**_ since the last commit in the PR and will test after any later commits.

## What does this pull request do?

Updated sql script to add desynthesis recipe for `Gigas Bracelets`

## Sources

- https://wiki.ffo.jp/html/7184.html
- https://ffxiclopedia.fandom.com/wiki/Gigas_Bracelets?oldid=319936

## Proof of level 57 Goldsmithing
I started a new character and leveled Goldsmithing 1 level at a time, attempting the synth with +3 Synth Support to find exactly what level it became synthable. Here are the last 2 videos showing it was not synthable at 29, but became synthable at 30, giving us the true level of the synth (57).

![image](https://github.com/user-attachments/assets/4ca4d080-f50b-43fa-b59e-3f23614332d0)

https://github.com/user-attachments/assets/72d7c3c9-2bda-4767-a2ba-dca94f369df0

https://github.com/user-attachments/assets/b49278af-0c3a-4c5c-a65f-f63ca685bc2e

## Steps to test these changes

- Be on a goldsmither 57+
- Use a lightning crystal on `Gigas Bracelets`

## Screenshots

![image](https://github.com/AirSkyBoat/AirSkyBoat/assets/43099213/3fdc00c8-9b86-4b6f-9580-bc1f72119c63)

![image](https://github.com/AirSkyBoat/AirSkyBoat/assets/43099213/a693313c-970f-4d4e-8301-f48686463aec)

2024-07-12 08:14 UTC, Xaver-DaRed commented
Changes look good.

Click the checkboxes accepting LSB's conditions and please, in the future, do not use a different repository (ASB) PR schema.

2024-07-13 17:42 UTC, Xaver-DaRed commented
So, after checking the links and digging around I can find absolutely no evidence of the recipe level.

So I cannot approve this in good faith. Most we can accept is setting the recipe goldsmithing level to 255, effectively existing in a disabled state, with a comment stating the recipe level needs to be retail verified.

2024-07-13 17:45 UTC, Xaver-DaRed requested changes

2024-07-13 17:45 UTC, Xaver-DaRed commented on sql/synth_recipes.sql
> +INSERT INTO `synth_recipes` VALUES (75534,1,0,0,0,60,0,0,0,0,0,4100,4242,14018,0,0,0,0,0,0,0,653,653,745,745,1,2,1,1,'Gigas Bracelets (desynth)');
Please set the goldsmithing level to 255 and add a comment stating the recipe needs retail verification for its lvl.

2024-07-13 17:46 UTC, Xaver-DaRed commented
An additional note: We cannot approve untested PRs. (Since the checkbox is unchecked)

2024-07-13 20:15 UTC, 9001-Sols commented
> An additional note: We cannot approve untested PRs. (Since the checkbox is unchecked)

I haven't had a chance to spin up LSB yet, all my development was done in ASB and I was asked to port the PRs over to here. As soon as I get LSB spun up and I have time to test, I'll check the box.

2024-07-14 23:37 UTC, 9001-Sols commented on sql/synth_recipes.sql
> +INSERT INTO `synth_recipes` VALUES (75534,1,0,0,0,60,0,0,0,0,0,4100,4242,14018,0,0,0,0,0,0,0,653,653,745,745,1,2,1,1,'Gigas Bracelets (desynth)');
I captured data from retail and will update my summary with the details. The correct level was 57.

2024-07-15 13:20 UTC, Xaver-DaRed approved these changes
I tested this myself after seing the evidence.

However, this is a one time thing. Next time you will need to test this yourself or find some1 willing to test it.

2024-07-15 14:48 UTC, 9001-Sols commented
> I tested this myself after seing the evidence.
> 
> However, this is a one time thing. Next time you will need to test this yourself or find some1 willing to test it.

Hey sorry, not trying to dump testing efforts on others.

Right now LSB is hosed when I launch it locally, as the retail install to capture data messed up LSB/ASB/Horizon setup. I log into a debug zone and GM commands don't work. I'm going to remake the database and try to do a fresh setup. I just haven't had time. As soon as I have LSB functioning I'll retest all my PRs (they were originally tested on ASB) and go ahead and check the box that things were tested.

2024-07-16 10:15 UTC, merged