Z's Trident Latent
LandSandBoat/server pull request #5997
Opened 2024-07-12 01:18 UTC by 9001-Sols

**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my PR will be ignored.
- [x] I understand I should leave resolving conversations to the LandSandBoat team so that reviewers won't miss what was said.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have _**tested my code and the things my code has changed**_ since the last commit in the PR and will test after any later commits.
## Please enter a player-facing description

Latent effect was added to `Z's Trident`

## Source:

https://wiki-ffo-jp.translate.goog/html/3911.html?_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=en

![image](https://github.com/user-attachments/assets/ffd7f1f4-e646-42ca-809c-681c17f78083)

## What does this pull request do? (Please be technical)

This adds support for a `during WS` latent trigger. The existing one also applied when TP was less than 1000, which isn't what we wanted for `Z's Trident`.

Additionally, it adds the `STR+12` latent to Z's Trident to be active during Weapon Skills
![image](https://github.com/AirSkyBoat/AirSkyBoat/assets/43099213/d11f6fb5-dd8f-462f-b91b-b4c6c564da69)

## Steps to test these changes

You can add a `printf` in the `weaponskills.lua` to print player STR during WS, here is a screenshot of me doing that:

![image](https://github.com/AirSkyBoat/AirSkyBoat/assets/43099213/cdafb31e-d1fc-47a0-859b-f4c9f09c2df8)

## Special Deployment Considerations

* No new considerations for fresh installs
* The script will need to likely be run manually for pre-existing installs, unless there is a migration process or something I can update

2024-07-12 01:44 UTC, WinterSolstice8 commented on src/map/latent_effect_container.cpp
> +bool CLatentEffectContainer::ProcessLatentEffect(CLatentEffect& , bool isDuringWs)
```suggestion
bool CLatentEffectContainer::ProcessLatentEffect(CLatentEffect& latentEffect, bool isDuringWs)
```

2024-07-12 01:44 UTC, WinterSolstice8 commented on src/map/latent_effect_container.h
>      bool ProcessLatentEffect(CLatentEffect& latentEffect);
Looks like you forgot to delete this second line

2024-07-12 02:02 UTC, 9001-Sols commented on src/map/latent_effect_container.h
>      bool ProcessLatentEffect(CLatentEffect& latentEffect);
Thanks! Was midway through porting this PR over from ASB and got pulled into Dynamis 😆

2024-07-16 17:28 UTC, 9001-Sols commented
I've re-tested this with a fresh LSB install after porting it from ASB and confirmed it is still working as intended:

First WS was with Gungnir
Second WS was with Z's Trident

![image](https://github.com/user-attachments/assets/90a3cd32-a076-48ef-bf33-057d718fa8e2)

![image](https://github.com/user-attachments/assets/67b7fe3c-36f0-4b4a-af7b-0d16568dd948)

2024-07-16 19:13 UTC, cocosolos requested changes

2024-07-16 19:13 UTC, cocosolos commented on sql/item_latents.sql
> +
This is out of order, can you move it up above Leviathan's Couse?

2024-07-17 02:04 UTC, WinterSolstice8 approved these changes

2024-07-19 09:56 UTC, Xaver-DaRed approved these changes

2024-07-25 12:52 UTC, merged