Refactor and expand gear_sets
LandSandBoat/server pull request #726
Opened 2021-09-16 00:09 UTC by neuromancerxi

This update brings gear_sets up to date with all gear sets currently in the game as of September 2021, including a number of lower tier sets that were missing as well as all AF3 90/109/119 sets.
Arbitrarily reorders/renumbers the set ids in Gearsets starting from lowest level armor set and moving upwards.
This serves little purpose other than to help me identify which sets were missing as I added them in.
Updated and lined up comments where possible.
Moved Jailer weapons to the end of the stack.
Updated Gearset logic to apply buffs to pets (Breeders set and SMN AF1 119 +2/+3 currently).
addGearSetMod() now expects a 0 for standard sets and a 1 for petmod sets (see examples in `doSpecialHandling` and `addGearSetMod`)
Updated Gearset logic to rename `cappedTierSets` to the more aptly named `specialHandlingSets`.
Updated Gearset logic to standardize AF3 set bonuses where possible, and manually defined the outliers.
Added in missing `specialHandlingSets` and ensured that migrated sets matched their new id after refactor.
Created new MODs for missing Empyrean Gear Sets:

Implemented with logic:
AUGMENT_ATTACK_HP
AUGMENT_DAMAGE_PET_HP
AUGMENT_SONG_STAT*

Place Holders: --TODO
AUGMENT_BLU_MAGIC
AUGMENT_CONSERVE_MP
AUGMENT_BLOOD_BOON
AUGMENT_COMPOSURE
GEOMANCY_MP_NO_DEPLETE

*Regarding AUGMENT_SONG_STAT, due to the way that songs are applied, this is implemented in three different ways (depending on the existing song script):

1. The Lions share have the AUGMENT_SONG_STAT value passed as subPower in the song, and applied in the effect.
2. For etude, subpower is in use. The value is passed instead via power (elements of songs match the stat buff) and the etude effect, remaining unchanged, applies the bonus within the power.
3. For carol, subpower is also in use. The `AUGMENT_SONG_STAT` value is multiplied by 100, added to the element value, then deconstructed in the effect. This ensures that the buff and the base value can be cleanly separated and applied. Details and logic are commented in the effect.

**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] that I agree to LandSandBoat's [Limited Contributor License Agreement](https://github.com/LandSandBoat/server/blob/base/.github/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I have **read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)**
- [x] that I've _**tested my code and things my code changed**_ since the last commit in the PR, and will test after any later commits

2021-09-16 00:37 UTC, TeoTwawki commented
> Arbitrarily reorders/renumbers the set ids in Gearsets starting from lowest level armor set and moving upwards.

There is a lot of this I wish had been separate commits, if not separate pr's. This is going to take a longer time to review cause of what re-sequencing all the IDs did to the git diff. At a minimum any future re-sequencing you do, please do as its own commit _before_ adding new stuff.

Semi-related: I am really regretting not taking a day to change the table format before something like this inevitably arrived.

2021-09-17 02:45 UTC, TeoTwawki commented
>  TeoTwawki requested review from zach2good, claywar and TeoTwawki and removed request for zach2good and claywar 1 minute ago 

go home github, you're drunk

2021-10-13 17:17 UTC, ShiyoKozuki commented
Can you remove the blue magic.lua changes?  I'll add it to my pr

2021-10-13 20:42 UTC, claywar requested changes
There's a lot going on here, and it seems sane.  What I'm curious about is the removal of some items overall.  Once that is understood, I'll get more granular.

2021-10-13 20:42 UTC, claywar commented on scripts/globals/effects/carol.lua
> +    local spower = effect:getSubPower()
Not as familiar with this code, but are we guaranteed that `spower`, with hundreds being subtracted is guaranteed to hit a single-digit?  Not sure where this is coming from.  Is this a bitfield?  If so, we should handle it as such.

2021-10-13 20:42 UTC, claywar commented on scripts/globals/gear_sets.lua
> +            {id =   1, items = {15042, 11402}, matches = 2, matchType = matchtype.any, mods = {{xi.mod.ATT, 5, 0, 0}, {xi.mod.RATT, 5, 0, 0}} },                        -- Gothic Gauntlets/Sabatons: A
Regarding formatting, If everything else is all over the place, why format id?

2021-10-13 20:42 UTC, claywar commented on scripts/globals/gear_sets.lua
> -    {id = 199, cappedTier = true},
Several sets were removed that don't exist in new work, is there a reason for this?

2021-10-13 20:42 UTC, claywar commented on scripts/globals/gear_sets.lua
> +    elseif (gearset.id == 69 or gearset.id == 219) then -- RDM AF3 90/109/119
Styling, no containing parens

2021-10-13 20:42 UTC, claywar commented on scripts/globals/gear_sets.lua
> +        if (matches >=2 and matches <= 3) then
Styling, spacing

2021-10-13 20:42 UTC, claywar commented on scripts/globals/gear_sets.lua
> +        elseif (matches > 3) then
parens

2021-10-13 20:42 UTC, claywar commented on scripts/globals/gear_sets.lua
> +        -- printf("[DEBUG] Enabling Special Handling | gearset: %u | mod %u %u", gearset.id, xi.mod.FASTCAST, modValue)
👍 Thanks for sane debug comments

2021-10-13 21:54 UTC, neuromancerxi commented on scripts/globals/effects/carol.lua
> +    local spower = effect:getSubPower()
That's correct. The values being passed are the [ID for the element](https://github.com/LandSandBoat/server/blob/3dfe1f76e9a5c4fe4392de6ffb77ea2bdc2fb4ef/scripts/globals/spell_data.lua#L65) plus a value of either 0, 100, 200, 300, or 400. See the individual songs/spells (e.g. lightning carol) for clarification.

2021-10-13 21:55 UTC, neuromancerxi commented on scripts/globals/gear_sets.lua
> +            {id =   1, items = {15042, 11402}, matches = 2, matchType = matchtype.any, mods = {{xi.mod.ATT, 5, 0, 0}, {xi.mod.RATT, 5, 0, 0}} },                        -- Gothic Gauntlets/Sabatons: A
The columns line up at the beginning of each line, so it made sense to me to at least try to clean it up where possible.

2021-10-13 21:56 UTC, neuromancerxi commented on scripts/globals/gear_sets.lua
> -    {id = 199, cappedTier = true},
The old IDs no longer align with the new ids, so they are all replaced/reordered with their new id. Each set that was present in the previous iteration is present in the new version, albeit with a new id.

2021-12-20 18:21 UTC, TeoTwawki requested changes

2021-12-20 18:21 UTC, TeoTwawki commented on src/map/lua/lua_baseentity.cpp
> +            } else {
```cpp
}
else
{
```

2021-12-20 18:21 UTC, TeoTwawki commented on src/map/lua/lua_baseentity.cpp
> +    } else {
```cpp
}
else
{
```

2021-12-20 18:22 UTC, TeoTwawki commented
apparently \*\*it hub decided my comments were a pending review in progress and never posted them till now.

2022-06-02 23:25 UTC, claywar commented
There are several merge conflicts with this PR.  Could you please resolve before we review?

2022-06-03 13:15 UTC, neuromancerxi commented
Working on breaking up this PR into smaller better commented chunks. If it's acceptable to do so, I will leave it open until it's been replaced by subsequent PRs.

2022-07-26 12:27 UTC, closed without merging